### ISSUE TITLE
Pedigree Improvements

### ISSUE THREAD

**Issue by gvannoy** [broadinstitute/seqr#1249]
It would be helpful to have the pedigrees in seqr display more information as info from Phenotips becomes more integrated. 

Information that would be ideal: ability to indicate an individual is deceased, addition of ages to individuals in pedigree (would need to be calculated from year of birth), indication of twin/multiple births 

I'd be happy to speak further about these ideas and help with input on design. Thanks!

**Comment by hanars** [comment]
Combining with some other tickets about pedigree images to make tracking work easier
Improve storage for images:
- Store pedigree images in db instead of on disk
- use pedigree.js in place of static images (https://ccge-boadicea.github.io/pedigreejs/)

Better handle half siblings. Correctly draw simple half-sibling cases, detect more complicated cases and raise an error.

https://github.com/broadinstitute/seqr-private/issues/567
