### ISSUE TITLE
Tagged variant missing from seqr search (AP4E1 p.Ser700Arg)

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#1423]
**Describe the bug**
Outside analyst tagged this recessive pair and I can’t replicate it in search. The p.Ser700Arg variant seems to be missing. Running 'gene search' from the saved variant is unable to return it. It's a high-quality variant and data was first loaded in Feb 2020. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0532_cmg_walsh_exomes_pmg/saved_variants/variant/SV0067208_1550915479_f029695_w,SV0067209_1550993379_f029695_w

**Scope of the bug**
I've never seen this before but I don't often re-search saved variants.

**Comment by hanars** [comment]
So whats really weird is that this variant does not appear to exist in the raw data, but the data has not been reloaded since the variant was first saved. The reason that variant is not coming back in any search is it doesn't appear to have ever existed in the data, I honestly have no idea how thats possible. @mike-w-wilson @chr-k do either of you know if there was anything weird about the walsh pmg index that could have caused it to be updated in place?

**Comment by ch-kr** [comment]
I don't know what happened with the index, but I just confirmed this variant is in the latest exomes MT:
![image](https://user-images.githubusercontent.com/19142091/90660521-0d627100-e214-11ea-9111-65d89caa7ccb.png)

**Comment by hanars** [comment]
so its definitely not in the index, which is really weird... @mike-w-wilson and I had discussed doing a reload of all the internal projects anyways so maybe this is just another reason on that list to reload

**Comment by hanars** [comment]
This compound het is now coming back from search. Not sure what caused this in the first place, but we reloaded data on 12/3 so thats probably what fixed it
