### ISSUE TITLE
Seqr search

### ISSUE THREAD

**Issue by jill-madden** [broadinstitute/seqr#1489]
Hi, we're variant searching a family on Seqr (MAN_1614) and the results generated are very minimal. When we open the filters further, I'm getting an error. Something seems off. Can you take a closer look? Thanks! 
![Screen Shot 2020-11-03 at 9 33 56 AM](https://user-images.githubusercontent.com/58273508/97999841-d3881c00-1db9-11eb-87cb-775167eeec1b.png)
![recessive opem](https://user-images.githubusercontent.com/58273508/97999848-d551df80-1db9-11eb-8dac-fab9abfbc57e.JPG)

**Comment by hanars** [comment]
I'll look a bit deeper, but in a first pass it seems to be that all the variants of interest in these genes are present in the unaffected sibling, which causes them not to be returned by recessive search. When I did the same recessive search that returned 0 results but changed the status of the sibling form "Unaffected" to "Unknown (?)" I did get 5 results: 
https://seqr.broadinstitute.org/variant_search/results/d76ed19890ca350d177a4d050c2ec994?page=1&sort=in_omim

When I did a search with all the same criteria except instead of filtering for recessive inheritance I filtered just whether or not the variant was in the affected individual, I got back 164 variants, and in a quick pass it looks like basically all the variants are also present in the unaffected sibling: https://seqr.broadinstitute.org/variant_search/results/f2157dcc4a2e7d35a8f7d934d281311f?page=1&sort=in_omim

**Comment by jill-madden** [comment]
Ah, thank you! Upon a closer look, the unaffected sibling is an identical twin, so that makes sense. Thanks for taking a closer look as it helped to connect the dots!

**Comment by hanars** [comment]
Ah, that explains it then!
