### ISSUE TITLE
Compound het might have more found variants than recessive in the same search

### ISSUE THREAD

**Issue by SimonLi5601** [broadinstitute/seqr#1552]
**Describe the bug**
We found in some cases that with all other parameters remain the same, Compound het might return more found number variants than recessive in the front end. It seems that standalone Compound het search won't go through the deduplicate. Also, the number for Compound het seems to be pairs of variants rather than numbers of variants.
Is this a concern if the number doesn't match?

**Comment by hanars** [comment]
We've never encountered that bug before, so its hard for me to debug without more information. In theory, the number of recessive variants is the number of compound hets plus the number of hom recessive plus x linked recessive, so that should always be greater than or equal to the number of compound hets, so if thats not happening something is broken

We want the number of compound hets to be the number of pairs, this is the desired behavior requested by our analysis team

**Comment by SimonLi5601** [comment]
Thanks, Hana! Yes, you might be right. It could be the data issues. But in general, what the deduplicate function is doing if the recessive should the sum of all of three?

**Comment by hanars** [comment]
deduplicate is supposed to combine variants from multi-index search across projects. it is not supposed to deduplicate recessive and compound het variants

**Comment by SimonLi5601** [comment]
Will close it for now. Thanks!
