### ISSUE TITLE
Question regarding PR #1486 - Privacy Policy and Terms of Service

### ISSUE THREAD

**Issue by tommyli** [broadinstitute/seqr#1653]
At MCRI, as part of our recent merge with upstream code, we noticed [new "Privacy Policy" and "Terms of Service" agreements](https://github.com/broadinstitute/seqr/pull/1486) were added for users to accept upon login.  Obviously both the "Privacy Policy" and "Terms of Service" is written for the Broad deployed instance in mind.  However, we would like to ask if there are anything that Broad would like enforced for "forked" deployed instances also, e.g. our non-public deployed instance at MCRI?

At MCRI, our Seqr instance is not accessible from the Internet (i.e. behind VPN).  Also, we have separate documents/processes to cover MCRI specific/equivalent "Privacy Policy"(s) and "Terms of Service"(s).  Depending on your response, we may customise the logic to disable this for our instance.  (e.g. set `SEQR_PRIVACY_VERSION` and `SEQR_TOS_VERSION` to -1 and bulk update `seqr_userpolicy` table with values of -1 or something similar).

**Comment by hanars** [comment]
We have no preference about enforcing terms of service for forked seqr deployments, so you should feel free to do whatever you want with it. 

One way you could change it on your end would be to change in setting.py `SEQR_PRIVACY_VERSION = 1.0` to `SEQR_PRIVACY_VERSION = os.environ.get('SEQR_PRIVACY_VERSION', 1.0)` and then update the docker compose environment to set that environment variable to null (and do the same for the TOS constant). Since that would be a non-breaking change for our seqr, we would be happy to integrate that if you put up a PR for it. I think that would be a little more stable for you guys since if we updated the version later on you wouldn't get any merge conflicts, but totally up to you how you want to go about this
