### ISSUE TITLE
Update variant display for genome structural variants

### ISSUE THREAD

**Issue by ShifaSZ** [broadinstitute/seqr#1834]
An example of a saved variant's information is displayed as below figure:
![image](https://user-images.githubusercontent.com/33550059/117048581-2434ef00-ace1-11eb-8c59-e69be0c63943.png)

The new structural variant information includes:
1. gnomAD ID and link to gnomAD page
2. SV genotypes (e.g. -/X)
3. SV type, SV type details for INS and CPX
4. CPX intervals
5. Show transcript consequences

**Comment by hanars** [comment]
As an overall comment, you should be marking up the UI differences on an existing exome SV variant, not on a SNP variant, because thats really what you will be changing. The SNP display remains unchanged, its the SV display thats going to need tweaking

gnomad SV frequency goes on the right hand side with the other frequencies. The ID will be used to construct the link that is the value (see the way the topmed value is a link)

SV type will already display as it was implemented for exomes SVs. The change you need to make is Sv detail and should do that by adding it next to or under the sv type (whichever looks better to you)

complex intervals will be shown under the position but above the seqr/gnomad/pubmed links

**Comment by ShifaSZ** [comment]
Thanks, Hana. I updated the layout picture. Any further comments will be helpful.

**Comment by ShifaSZ** [comment]
Preliminary SV variant display layout ([sourc code branch](https://github.com/broadinstitute/seqr/tree/sv-variant-display)):
![image](https://user-images.githubusercontent.com/33550059/119377533-3cb67a80-bc8b-11eb-8b7a-f6b5fc9adc77.png)
