### ISSUE TITLE
Variant search issue

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#1872]
**Describe the bug**
I saved my own recessive permissive search (using the criteria for recessive permissive in the RGP workflow) and tried to look for the "answer" to case 0985 in Exome Project L (compound het Pro2219Leu;Pro126Leu variants in PKD1). This returned 17 variants including the Pro2219Leu variant and a 3'UTR variant in PKD1, but Pro126Leu was not there. I then clicked on Gene Search to see all variants in PKD1 and the Pro126Leu variant STILL doesn't show up. However, if I just apply my saved recessive permissive search again after doing the gene search, all of the sudden there are 48 variants and the Pro2219Leu and Pro126Leu variants are both returned. I've replicated this multiple times.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/d11e3211b3e34ef872c2637f34f1ace0?page=1&sort=pathogenicity

**Scope of the bug**
Other analysts have reported fluctuating numbers of variants being returned from their variant searches as well

**Screenshots**

**Comment by hanars** [comment]
do you know if you are using the same sort for each search? As in, does changing the sort change the number of variants returned, or no?

Also, do you have any examples of this in "real"projects? The test projects are pretty badly maintained so I wonder if it might be a data integrity issue with those

**Comment by Caustint** [comment]
I haven't touched the sort by so it was sort by pathogenicity for all.

If I use the same saved recessive permissive filter on the "real" version
of this case in CMG_Manton_Exomes, I get 17 variants but the Pro126Leu
variant doesn't come up:
https://seqr.broadinstitute.org/variant_search/results/181e5f3c4c2c821ac643f92f02b345d7?page=1&sort=pathogenicity
The gene search does return Pro126Leu in that project. But if I run the
recessive permissive filter again after the gene search I now get 10
variants:
https://seqr.broadinstitute.org/variant_search/results/73b66de0f77a27fc95d4f16c1b09b11b?page=1&sort=pathogenicity

I think Lynn was going to add examples from her cohorts.

*Christina Austin-Tse, PhD, FACMG*
Analysis Team Lead, Rare Disease Group, Broad Institute of MIT and Harvard
Clinical Molecular Geneticist, Center for Genomic Medicine, Massachusetts
General Hospital
Instructor in Pathology, Harvard Medical School
Pronouns: She/her

**Comment by lynnpais** [comment]
Hi all,

Here's one more example from an active CMG project. 

Two missense variants (<0.01 AF) in HELZ2 are tagged - https://seqr.broadinstitute.org/project/R0365_cmg_scott_exomes/saved_variants/family/F026349_sco_ped75/Tier%202%20-%20Novel%20gene%20and%20phenotype
<img width="1178" alt="Screen Shot 2021-05-21 at 11 25 17 AM" src="https://user-images.githubusercontent.com/37872186/119161356-3f189a80-ba27-11eb-923b-ab6f3bf4c46c.png">


However, when you run a standard recessive search, neither of the variants are returned - https://seqr.broadinstitute.org/variant_search/results/580082ff2f5294ab37d681b116619129?page=1&sort=splice_ai
(also related to the sort by SpliceAi issue? but it is affecting active searches)

A search for ANY variant in HELZ2 returns only 1 of the 2 variants. I can no longer share the link or a picture, because now I am getting a transport error.
<img width="1231" alt="Screen Shot 2021-05-21 at 11 28 09 AM" src="https://user-images.githubusercontent.com/37872186/119161755-a8001280-ba27-11eb-8303-a32366efd60e.png">

Transport errors are popping up across multiple cohorts.

**Comment by williamphu** [comment]
Hi Hana, I'm also getting a "circuit_breaking_exception" when loading Seqr projects to the website.
![image](https://user-images.githubusercontent.com/17106856/119192834-bada0d80-ba4e-11eb-9001-a6ca627370d3.png)

This happened for the INMR WGS project, https://seqr.broadinstitute.org/project/R0293_inmr_neuromuscular_disea/project_page , with this ES index: `r0293_inmr_neuromuscular_disea__wgs__grch38__variants__v02__vcfv18__20210519`. On further attempts to load, it appears that another error crops up:

![image](https://user-images.githubusercontent.com/17106856/119193280-68e5b780-ba4f-11eb-98e2-c225f82b456e.png)

There was one attempt that did not throw an error, but it doesn't look like new samples were added (which could be my issue).

**Comment by hanars** [comment]
Search issues should be resolved. If folks could check and verify if everything is fixed that would be appreciated! No need to test out adding indices, just the searches

**Comment by hanars** [comment]
Closing this out as these searches are returning as expected now and the underlying database issue has been fixed. Feel free to reopen if you find another case like this
