### ISSUE TITLE
Intronic variant in a coding variant search

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1880]
**Describe the bug**
Intronic variants returned in a search for variants in coding regions only

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/9e6ba758a15bfe015132df5e86f10e05?page=1&sort=xpos

**Scope of the bug**
Noticed across multiple projects, but have just this example for now.

**Screenshots**
<img width="1195" alt="Screen Shot 2021-05-24 at 1 41 42 PM" src="https://user-images.githubusercontent.com/37872186/119386735-f1559980-bc95-11eb-83e3-b9a2a192779e.png">

**Comment by hanars** [comment]
So the canonical transcript for this variant is intronic, but if you click in to the the transcripts you can see that there is one transcript that is annotated as a splice_region_variant which is why this variant is being returned.

We have an open feature request for making it clearer which transcripts match the sort, instead of always showing the canonical/ chosen transcript regardless of whether it matches the search:
https://github.com/broadinstitute/seqr/issues/229
