### ISSUE TITLE
Bump IGV JS to the latest version

### ISSUE THREAD

**Issue by larrybabb** [broadinstitute/seqr#1923]
set up meeting with @hanars to initiate project

**Comment by hanars** [comment]
To update the version (from to ui/ folder): `npm install --save igv@latest`

Settings updates:
In order to prevent our CSP policies from blocking resources, you will need to update some settings in settings.py. Heres the changes I had to make last time I attempted to bump the version: https://github.com/broadinstitute/seqr/commit/b11bbabad32fcb658958311da4cd33dd461296f9#diff-dc2c79b556e950acc7dea90175fd5febba22bf9fa4faaba1b61c3b3d5acdc9e9 (this branch already behind a couple minor versions so I wouldn't use this branch for anything, but its a good reference for how to get the CSS and requests working)

thats as far as I got! You should be able to click "show reads" on any of the real saved variants and see IGV load locally the way it currently does on production. I would make sure this is working for you locally on the dev branch before you start updating things, just to be sure
