### ISSUE TITLE
match display for x-linked recessive to actual searched parameters

### ISSUE THREAD

**Issue by WendyZhang05** [broadinstitute/seqr#1932]
Hello, 

In x-linked recessive variant search, I saw allele count in the frontend is set as below. A unaffected mother is set to ref_alt (1). 
[X_LINKED_RECESSIVE_FILTER]: {
    [AFFECTED]: ALT_ALT,
    [UNAFFECTED]: HAS_REF,
    father: REF_REF,
    mother: REF_ALT,
  }
However, once it is sent to backend, unaffected mother is still set as has_ref(0-1) and only unaffected male is set to ref_ref. https://github.com/broadinstitute/seqr/blob/002a96ccb341b4d112f1b906cf63c85c7e1e1df6/seqr/utils/elasticsearch/es_search.py#L1138. 

If you see the results of x-linked recessive variant search, you can see unaffected mother with allele count 0 is also show up. This make users confusing since in frontend search form, unaffected mother is set to 1. 

I also have another question about compound hets search. In the instruction it says "If parents are not present, this method only searches for pairs of heterozygous variants; they may not be on different haplotypes." So, if parent exists, how it checks haplotypes. It seems I cannot find this logic checking parents in code. Can you please show me in code how it checks haplotypes in compound hets?

**Comment by hanars** [comment]
Yes, it appears there is a mismatch between what is displayed in the inheritance search panel and what the actual x-linked recessive search behavior is. The actual search behavior is correct - it is consistent with how recessive searches are generally applied in seqr. I will update the display to show 0-1 instead of 1 for the mother in x-linked search to make this clearer

For compound hets with parents, the original elasticsearch query returns all possible compound hets, and then we filter out those where the haplotypes are not correct: https://github.com/broadinstitute/seqr/blob/master/seqr/utils/elasticsearch/es_search.py#L803

**Comment by hanars** [comment]
The display has been updated to match the search behavior
