### ISSUE TITLE
Permissions error setting up local install

### ISSUE THREAD

**Issue by jules-o** [broadinstitute/seqr#1940]
Hi,

I'm trying to set up a new local install with docker on Ubuntu 20.04, but the elasticsearch container exits straight away as "unhealthy". Elasticsearch container logs show permission denied error (copy attached).

If I change the permissions on the data directory and try again then setup appears to complete and I can create the superuser, but then I get a blank page when I go to localhost - log from seqr container also attached. 

I have LZMA command line tool 9.22 and LZMA SDK 9.22

What am I doing wrong?

[docker_elasticsearch_log.txt](https://github.com/broadinstitute/seqr/files/6805081/docker_elasticsearch_log.txt)
[docker_seqr_log.txt](https://github.com/broadinstitute/seqr/files/6805082/docker_seqr_log.txt)

**Comment by hanars** [comment]
So it sounds like the issue with elasticsearch was the directory permission, and you fixed that. For seqr, the logs actually show a successful 200 response for the status endpoint, which means all dependent services including elasticsearch and your database are running properly, which is good. I wonder if the issue is actually an error in the javascript, as I'm not seeing anything in the server side logs. Can you try and send me a screenshot/ copy-paste of the console output from the browser?
