### ISSUE TITLE
Optimization of gCNV viewer speed in seqr 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2079]
gCNV viewer in seqr 
The gCNV viewer is very slow to load. It takes a long time (multiple clicks of >30 sec) to zoom out, reload the tracks, and have a better view of the CNV and surrounding region (compared to when visualizing in TGG viewer directly), which makes it hard to use. Is it possible to optimize the speed?

**Comment by ShifaSZ** [comment]
The loading latency data for the tgg-viewer and the seqr gCNV viewer are shown below figures.
The latencies for loading a gCNV track in seqr:
![image](https://user-images.githubusercontent.com/33550059/131680297-5ca1c364-d45a-4125-aa26-c428b48d633c.png)

The latencies for the tgg-viewer:
![image](https://user-images.githubusercontent.com/33550059/131680505-f75e3f47-0c38-43fd-b62d-6a356bd6aebe.png)

 Generally, the delay to load the gCNV data from the network for seqr is much longer than that for tgg-viewer. The main reason for that is because seqr uses its backend as a proxy to load the data from a Google Storage bucket while the tgg-viewer loads the data from the frontend directly.

**Comment by ShifaSZ** [comment]
The seqr data loading proxy is the bottleneck. It's been proved experimentally changing the seqr to load the data directly from the frontend. The seqr data loading latencies in the experiment are as blow.
![image](https://user-images.githubusercontent.com/33550059/131684372-42463b59-e4d5-4920-9540-53c9c1dbd3b9.png)

**Comment by ShifaSZ** [comment]
There are ways to improve seqr IGV performance:
1. Allow the seqr frontend to get the credential that is needed to access Google Storage. (very unlikely because of the security of seqr system)
2. Make the gCNV data publicly accessible on `gs://seqr-datasets-gcnv/GRCh38/RDG_WES_Broad_Internal` so that seqr can load it from the frontend. (also unlikely because of the data protection)
3. Optimize the data loading proxy by changing to use an HTTP API rather than a `gsutil` command to load the data from Google Storage. (not sure it would work or not yet)
4. Add a cache for the proxy? I can improve the performance for subsequential data loading but won't improve the first-time loading.

**Comment by hanars** [comment]
We can not make any changes to where data is stored or who has permission to access that data, as I made clear last time we discussed this. As such you are correct that 1 and 2 are not going to be working options.

3 is interesting to me - I think it *should* be possible and I've always felt that using the `gsutil` to essentially print out the data was probably not the best approach. I think its worth at least trying to see if you can get this working

4 would speed things up for subsequent requests, but like you say its not going to improve first time loading data, which is most of the loading we do so not sure its worth the time investment

**Comment by ShifaSZ** [comment]
The result of replacing `gsutil` with an HTTP API is as below. It has a big improvement but is still around two times slower (latency doubled) than loading data from the frontend.
![image](https://user-images.githubusercontent.com/33550059/131714467-d4c9c18f-4bd9-451d-a755-078536f5b77a.png)

**Comment by hanars** [comment]
more importantly to how slow it is relative to loading from the frontend (which we can't do) is how slow it is relative to what we currently have? Is it 5 times faster? 1.5 times faster? Do we think its fast enough to be usable, or do we think we still need to invest in further optimizations?

**Comment by ShifaSZ** [comment]
When using the streaming mode for requesting the Google Storage, the latencies for large packages are shortened by 1/3 comparing to the non-streaming mode. The difference for the small package is small.
![image](https://user-images.githubusercontent.com/33550059/131739816-1dfaccbd-9315-49ae-98f9-c55f4d0b5f8f.png)

**Comment by ShifaSZ** [comment]
> more importantly to how slow it is relative to loading from the frontend (which we can't do) is how slow it is relative to what we currently have? Is it 5 times faster? 1.5 times faster? Do we think its fast enough to be usable, or do we think we still need to invest in further optimizations?

Good questions. Right now, we can achieve 1.5 times slower than the direct frontend loading. Maybe, that is the best we could do considering that we load the data over the network twice rather than once.

**Comment by hanars** [comment]
yes, but to repeat my question, how much faster are these optimizations relative to what we actually have right now in seqr. I don't really care how we are doing relative to a theoretical upper bound, I care how we are doing  relative to the current, real world, performance

**Comment by ShifaSZ** [comment]
The rough calculation result is that the optimizations including the streaming mode achieve 6 times faster than what we currently have in seqr.

**Comment by hanars** [comment]
thats amazing! I would suggest you clean up, test, and PR that code and we take it live. Then we can ask the analysts to take another look and see if its fast enough for them

**Comment by hanars** [comment]
The reference tracks https://seqr.broadinstitute.org/api/igv_genomes/broadinstitute.org/genomes/seq/hg38/hg38.fa.fai and https://seqr.broadinstitute.org/api/igv_genomes/org.genomes/hg38/annotations/cytoBandIdeo.txt.gz are quite slow now, so leaving this open to track fixing that

**Comment by ShifaSZ** [comment]
The `igv_genomes_proxy` API doesn't use the stream mode. Maybe it can be better by changing to the stream mode.

**Comment by ShifaSZ** [comment]
The performance of opening gCNV tracks from `seqr.broadinstitute.org` is measured as below. The download time is much larger than that I tested locally. It maybe is because of the Google storage proxy.
<google-sheets-html-origin><style type="text/css"></style>
data|size|time
-- | -- | --
hg38.fa.fai | 20.2 kB | 446 ms
cytoBandIdeo.txt.gz | 10.7 kB | 280 ms
hg38_alias.tab | 28.2 kB | 503 ms
GRCh38%2Fgencode%2Fgencode_v32_knownGene.sorted.txt.gz.tbi?alt=media | (disk cache) | 4 ms
refGene.sorted.txt.gz.tbi | 131 kB | 3.59 s
gs%3A%2F%2Fseqr-datasets-gcnv%2FGRCh38%2FRDG_WES_Broad_Internal%2Fv3%2Fbeds%2Fcluster__5.bed.gz.tbi | 514 kB | 2.99 s
hg38.fa?someRandomSeed=0.9syxdoqecfl | 51.9 kB | 3.15 s
GRCh38%2Fgencode%2Fgencode_v32_knownGene.sorted.txt.gz?alt=media&someRandomSeed=0.fjfxy1sc9aw | 54 B | 156 ms
GRCh38%2Fgencode%2Fgencode_v32_knownGene.sorted.txt.gz?alt=media&someRandomSeed=0.o77crphx39p | 14.8 kB | 203 ms
GRCh38%2Fgencode%2Fgencode_v32_knownGene.sorted.txt.gz?alt=media&someRandomSeed=0.lujwlwlypch | 54 B | 110 ms
GRCh38%2Fgencode%2Fgencode_v32_knownGene.sorted.txt.gz?alt=media&someRandomSeed=0.txvps4ziddc | 681 kB | 293 ms
gs%3A%2F%2Fseqr-datasets-gcnv%2FGRCh38%2FRDG_WES_B…%2Fcluster__5.bed.gz?someRandomSeed=0.2wp0pg13rsj | 808 B | 525 ms
gs%3A%2F%2Fseqr-datasets-gcnv%2FGRCh38%2FRDG_WES_B…s%2Fcluster__5.bed.gz?someRandomSeed=0.orucbiihik | 13.1 kB | 163 ms
refGene.sorted.txt.gz?someRandomSeed=0.q4dkzytcxx | 814 B | 253 ms
gs%3A%2F%2Fseqr-datasets-gcnv%2FGRCh38%2FRDG_WES_B…s%2Fcluster__5.bed.gz?someRandomSeed=0.buvkmozvwg | 808 B | 194 ms
refGene.sorted.txt.gz?someRandomSeed=0.c224vuyb5ep | 15.0 kB | 308 ms
gs%3A%2F%2Fseqr-datasets-gcnv%2FGRCh38%2FRDG_WES_B…s%2Fcluster__5.bed.gz?someRandomSeed=0.nfh3gms8u3 | 5.0 MB | 11.31 s
refGene.sorted.txt.gz?someRandomSeed=0.31ab9c04snh | 814 B | 11.09 s
refGene.sorted.txt.gz?someRandomSeed=0.rw0zzddlz1 | 300 kB | 1.13 s
gs%3A%2F%2Fseqr-datasets-gcnv%2FGRCh38%2FRDG_WES_B…%2Fcluster__5.bed.gz?someRandomSeed=0.giq7v0i2z2s | 808 B | 215 ms
gs%3A%2F%2Fseqr-datasets-gcnv%2FGRCh38%2FRDG_WES_B…%2Fcluster__5.bed.gz?someRandomSeed=0.2hez118vl8q | 5.0 MB | 20.48 s
gs%3A%2F%2Fseqr-datasets-gcnv%2FGRCh38%2FRDG_WES_B…%2Fcluster__5.bed.gz?someRandomSeed=0.ueeo2o223ol | 808 B | 313 ms
gs%3A%2F%2Fseqr-datasets-gcnv%2FGRCh38%2FRDG_WES_B…%2Fcluster__5.bed.gz?someRandomSeed=0.4a1zr7i2b2x | 5.0 MB | 19.24 s
gs%3A%2F%2Fseqr-datasets-gcnv%2FGRCh38%2FRDG_WES_B…s%2Fcluster__5.bed.gz?someRandomSeed=0.2qk189b5j8 | 808 B | 257 ms
gs%3A%2F%2Fseqr-datasets-gcnv%2FGRCh38%2FRDG_WES_B…s%2Fcluster__5.bed.gz?someRandomSeed=0.usrzaqsbbs | 5.0 MB | 20.42 s
gs%3A%2F%2Fseqr-datasets-gcnv%2FGRCh38%2FRDG_WES_B…s%2Fcluster__5.bed.gz?someRandomSeed=0.so7l0ipk9l | 808 B | 197 ms

**Comment by ShifaSZ** [comment]
I summarized some findings last week in a document at https://docs.google.com/document/d/1XyVnaYNWyTYZEUE5faS0KAzxs_nMq1FSpP_1XT0EFys/edit#heading=h.mjeq5orswrks.
We could do further optimizations listed as below:
- Firstly, we must figure out how to improve the performance of the “parseFloat” function by upgrading the core js library.

- Secondly, we may split the gCNV datasets into more clusters so that each cluster has fewer samples.

- And then we may suggest IGV do some improvements for gCNV:
  - One is to load the data for one time and reuse them when zooming in/out or changing location in the same chromosome.
  - The other further optimization is to only load the gCNV data within or close to the visible window rather than load all data within the chromosome.

**Comment by Glemiret** [comment]
Yes I can load the track now. It took 26 seconds to initially load the gCNV track and about 19 seconds every time I am zooming out to load the track again. The initial view did not show the full CNV however so that would definitely help reduce the number of necessary "zoom out" if it did and be more efficient (that is another GitHub ticket, https://github.com/broadinstitute/seqr/issues/2078). So my impression is that this is faster and more usable. thanks

**Comment by hanars** [comment]
Great! However, the ticket for showing the full CNV is closed because I thought we had already implemented it - can you comment on that ticket with an example of a variant where it did not load the full CNV initially? I want to make sure we fix that 

Otherwise, closing out this ticket as performance is adequate. We can always make another ticket in the future if we want to try and improve performance beyond the minimum standard we've achieved here

**Comment by Glemiret** [comment]
Is the gCNV track now available for all CNVs on exomes? I only see the option of clicking to view gCNV on BEG_146 (the initial test project we had) and on BEG_146, the CNV does not fully load on the initial view.
