### ISSUE TITLE
Bug report, variant has no tag in tsv list

### ISSUE THREAD

**Issue by sannagudmundsson** [broadinstitute/seqr#2086]
This is a bug report, 

1-145826478-G-A, family RGP_421 as an example

As far as I can tell [1-145826478-G-A](https://seqr.broadinstitute.org/variant_search/results/aa0024d8af1025d9974ace6f752cbed2?page=1&sort=xpos) variant has a review tag in seqr. But when i download "[all RGP variants](https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants)" or "[all Review tagged RGP variants](https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/Review)" as a tsv file the "Review" tag is not listed in column "tags". The column is empty. What's the reason for this tag not being stated in the tags column?

No tag when [downloading all RGP variants here](https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants), row 182.
No tag when [downloading all RGP review variants here](https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/Review), row 146. (but it is listed as review as I have selected to only show review tags)
but
Tag [is here](https://seqr.broadinstitute.org/variant_search/results/aa0024d8af1025d9974ace6f752cbed2?page=1&sort=xpos) when I search for the variant and download the tvs for only that variant here (tags_1, which is the one for family RGP_421)

Using seqR to filter RGP variants with review tag I get 1610 unique missense variants. 223 of them do not have the review tag noted in the "tags" column. 

thanks
Sanna

**Comment by hanars** [comment]
There is a bug downloading tags for compound hets. When a variant comes up by itself, as it does when you search for the variant alone, the tag is shown on the variant with no indicator that it is part of a compound het and downloads correctly. However, when you download from a page where it is correctly showing the compound hets (for that variant you can see it on the family variants page: https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F021469_rgp_421), it for some reason is only downloading the tags that are for the individual variants and not the tags that are shared between the compound hets. This is a bug- they should be downloading with all their tags. I should have this fixed by the end of the week

**Comment by sannagudmundsson** [comment]
Thank you Hana, I'll wait to download the data again once it is updated.
*---*
*Sanna Gudmundsson, Ph.D., Wallenberg Postdoctoral fellow, O'Donnell-Luria
Lab*
Program in Medical and Population Genetics, Broad Institute of
Massachusetts Institute of Technology and Harvard, Cambridge, MA, USA
Division of Genetics and Genomics, Boston Children's Hospital, Harvard
Medical School, Boston, MA, USA
Analytic and Translational Genetics Unit, Massachusetts General Hospital,
Boston, MA, USA
***@***.***
***@***.***

**Comment by hanars** [comment]
This is fixed now
