### ISSUE TITLE
Support Panel App confidence levels when filtering variants by location

### ISSUE THREAD

**Issue by david-ma** [broadinstitute/seqr#2119]
The next feature I'd like to work on is allowing users to select "Green", "Amber" or "Red" confidence level genes when they have selected a Panel App gene list.

![Screen Shot 2021-09-16 at 12 33 59 am](https://user-images.githubusercontent.com/3320713/133453786-7654142c-5d6e-4546-b424-a9bbda2fdc70.png)

Is this an ok design? The "Genes/ Intervals" section would react to the checkboxes being ticked/unticked. And I would make the Panel App section visibly disabled if the gene list selected was not a Panel App list, and add a tooltip to explain what Panel App is.

Most of the other variant search forms do not have reactive components, should the checkboxes be a dropdown in the header, or are they ok in the form area?

**Comment by david-ma** [comment]
It would also be good to show the user the confidence level of each gene using Textarea Highlighting, but this would require adding this library: https://codersblock.com/blog/highlight-text-inside-a-textarea/

<img width="669" alt="Screen Shot 2021-09-16 at 12 42 24 am" src="https://user-images.githubusercontent.com/3320713/133455023-56ec300d-244c-456b-8453-066c0b828404.png">

**Comment by hanars** [comment]
I would want @anneodonnell to weigh in on any UI changes before I give the OK. 

My slight preference would be that the Panel App section is entirely hidden if a panel app gene list isn't selected, rather than greying it out with a tooltip. I'm also not sure how I feel about highlighting in a text area - that library looks kind of hacky to me. It might be worth rethinking how we show gene lists in this filter entirely

**Comment by david-ma** [comment]
Do you mean 3 text boxes like this? It might be clearer to the user. They would be able to clearly see which genes belong to which set, and the editable text would be easy to copy+paste.

![Screen Shot 2021-09-30 at 9 59 26 am](https://user-images.githubusercontent.com/3320713/135364385-814eb5e4-748e-4fcf-bd14-3c2db148718f.png)

**Comment by hanars** [comment]
> Do you mean 3 text boxes like this? It might be clearer to the user. They would be able to clearly see which genes belong to which set, and the editable text would be easy to copy+paste.

Yeah I like this approach better. Maybe we make the color names in the text box label their own color (i.e. the word "Green" in "Green Genes/ Intervals" would be in green, etc)

Also, "Exclude locations" is all-or-nothing behavior so we would still only want their to be one checkbox for that

**Comment by tommyli** [comment]
@hanars - Looking at the code, I think dynamically adding and removing the text areas would be the most intrusive to the UI code.  Do you have any good examples in Seqr of dynamic forms?  The checkbox group in the first screenshot above would be simpler because even we could dynamically show/hide the checkbox group a the rest of the form components/structure would remain static.  Thoughts?

**Comment by hanars** [comment]
> I think dynamically adding and removing the text areas would be the most intrusive to the UI code. 
I don't really see how checkboxes being conditionally shown/ disabled is any less intrusive than having text boxes shown/ hidden

> Do you have any good examples in Seqr of dynamic forms? 

I don't think of this so much as a dynamic form as dynamic search panel content. The inheritance panel, for example, shows custom genotype filtering options if the user has only added one family to the search, but shows that custom inheritance is disabled if they add more families

**Comment by hanars** [comment]
Resolved in https://github.com/broadinstitute/seqr/pull/2376
