### ISSUE TITLE
Discrepancy between SV coordinates and genes listed

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#2141]
**Describe the bug**
An SV deletion called in MC18100 is listing >30 genes as affected but only 4-5 are within the called genomic coordinates. Spot checking the addition genes, they are nearby but outside the called SV. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0451_cmg_walsh_exomes_microce/saved_variants/variant/SV0097878_9136827574_f023512_m

**Screenshots**
![image](https://user-images.githubusercontent.com/44381119/134953441-d2fcd5ee-06ea-4081-ab6c-3e8947886090.png)
![image](https://user-images.githubusercontent.com/44381119/134953488-8f66c89f-ed1f-467e-8da0-6e6c4e6b83f2.png)

**Comment by hanars** [comment]
This is the result of how we combine SVs that are called in multiple samples within the project. If you search for this variant across all families, you see that it is called in 10 different families with different coordinates for each call. See the last variant in this search:
https://seqr.broadinstitute.org/variant_search/results/20f213ff22b4e69d77e125a493f52854?page=1&sort=xpos

In seqr, we added functionality so if you save a variant in a particular family, we only show the coordinates for that family's SV, whereas if you search it across all families it shows the coordinates for the entire SV. If you hover over the sample in the search results I linked, you will actually see that it shows the start and end coordinates that are shown on the saved variant you linked. Unfortunately, it appears that the gCNV caller considers these SVs to be "the same" even though they are really differen tin sze - the "parent" SV I linked to is 782kb across 53 genes, but in the family you actually saved it is only 38.8kb

I can update the seqr loading code so we can adjust the genes we show in these cases, the same way we adjust the coordinates and number of exons. However, that will involve re-loading the data which is time consuming. We are planning to reload all exome SV projects sometime next month, so this won't *actually* end up fixed in seqr until then

In the meantime, this SV in this sample is only overlapping the following genes: 
AJM1, EDF1, MAMDC4, PHPT1, RABL6

**Comment by hanars** [comment]
This issue is now fixed. In this particular case, it looks like this deletion is no longer called in the family you reported. However, when you look at the variant for the whole project you see it as the last variant here listed as 436 exons in 53 genes https://seqr.broadinstitute.org/variant_search/results/e69bb8400343720664c89864de6fc1b8?page=1&sort=xpos

but when you look at it in this one family it is listed as 314 exons in 42 genes, correctly showing only the genes actually overlapped by this particular family's deletion
https://seqr.broadinstitute.org/variant_search/variant/suffix_323576_DEL_2/family/F023622_mc39000
