### ISSUE TITLE
Bulk Edit Individual Metadata options don't match manual edit options and importing FALSE does not work

### ISSUE THREAD

**Issue by ctmarvin** [broadinstitute/seqr#2158]
For several fields on the Bulk Edit Individual Metadata page the import options "true, false, or blank if unknown" do not match the manual edit options "Yes, No, Unknown".

Attempting to bulk import these fields using TRUE correctly flags respective fields as "Yes" however attempting to bulk edit fields as FALSE seems to result in no changes to individual metadata i.e. leaves them as "Unknown" rather than "No".

These are the fields affected:
Consanguinity
Other Affected Relatives
Fertility medications
Intrauterine insemination
In vitro fertilization
Intra-cytoplasmic sperm injection
Gestational surrogacy
Donor egg
Donor sperm

**Comment by hanars** [comment]
The reported bug has been fixed, specifying false will now correctly sets the value instead of leaving it unspecified. 

The values expected in the bulk upload match what is downloaded in the template data, and there is no particular reason why the display in the UI needs to perfectly match the values for bulk editing (its not like you should ever be copy-pasting from the UI into the upload file), so we will be leaving the allowed values as they currently are

**Comment by anjalijain22** [comment]
Hi @hanars , I'm having the same issue described here with the Consanguinity column (not sure if its impacting other columns too): bulk import with TRUE correctly flags Consanguinity fields as "Yes" however attempting to bulk edit fields as FALSE leaves it as "Unknown" rather than "No". I also find that the fields correctly populate if the template is in CSV but run into these issues if the template is in excel format.

**Comment by hanars** [comment]
If it is an issue in excel and not csv the most likely explanation is that what excel is showing you when you look at the file is not what is actually in the raw file itself - excel often has formatting turned on so that it formats certain values differently for display. However, when ingesting an excel file that display-only formatting is lost. There is no reasonable way for seqr to parse anything from a file other than its raw values and as such can not support this - I would recommend that you save any excel files as csvs or tsvs , confirm tha the raw data is properly formatted, and then upload those files instead
