### ISSUE TITLE
Add LOF and CG structural variant annotations from gCNV dataset to loading pipeline and seqr

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2267]
**Is your feature request related to a problem? Please describe.**
Add genes_LoF and genes_CG to seqr loading pipeline. I guess I wasn't expecting the data in quite this format - we had initially planned to include this to assign a structural consequence to gCNV variants like we have for WGS SV data. 

**Describe the solution you'd like**
As a first implementation, I was thinking is a variant has an entry for
genes_LOF corresponds with loss of function structural consequence
genes_CG corresponds with copy gain structural consequence

**Describe alternatives you've considered**
We might be able to use this as an annotation later but the immediate use case is using to add structural consequence annotations to SVs. 

**Additional context**

**Comment by hanars** [comment]
This format of genes_CONSEQUENCE is actually how the raw data is delivered for SV VCF's so thats fine for us, it actually makes it easier to implement this in a way thats consistent between the two data types

One question I have - do we want the consequence filtering to apply the same for exomes and genomes? We are currently in the process of separating the SV types so they are different for exomes and genomes so we can filter on them separately, which is why I ask

**Comment by anneodonnell** [comment]
I think we should keep them separate. We don't think they are going to work as well for exomes so likely won't use them in quite the same way.

**Comment by hanars** [comment]
Blocked on the VCF formatting issues identified in https://github.com/broadinstitute/seqr/issues/2268

**Comment by hanars** [comment]
Now blocked on an additional issue where the columns contain gene symbols instead of ensembl IDs. This should be resolved later this week
