### ISSUE TITLE
Load gCNV data in CMG_Fajgenbaum_WES

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2268]
**Describe the bug**
More a test to find bugs, it's worth trying to load data in CMG_Fajgenbaum_WES first - this project has exome data but did not have gCNV data loaded previously so should be a clean project to try this loading. 

I talked with Julia and she said the STRVCTVE pipeline has changed but she will talk to William about annotating the new gCNV callset with these scores, which we need before we move to data loading. Hopefully he will have time next week (though depends how easy it is to figure out)

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0531_cmg_fajgenbaum/project_page

**Comment by hanars** [comment]
Considering this blocked until we have STRVCTVE, but good to have a ticket for this to track that this work is coming soon

**Comment by hanars** [comment]
@anneodonnell there are a couple breaking changes since the last callset: 

- In the last callset there was a column "genes_any_overlap_ensemble_id" which contained the ensemble IDs for overlapping genes. This callset only contains a "genes_any_overlap" column which contains the gene symbols. We could write code to map symbols back to their ensembl IDs similar to what we do for genome SV data, but it would be much better if we continued to have the ensemble IDs delivered to us
- The sample ID formatting is very inconsistent. Last time, all the sample IDs were in the format `<prefix>_<sample_id>_v<N>_WES_GCP` (i.e. C2071_WAL_MC23800_MC23801_v2_Exome_GCP). This time some of them are still formatted that way but some of them aren't and appear to just be the plain sample ID.  We either need everything formatted, or nothing.

**Comment by hanars** [comment]
breaking changes have been resolved with the latest data delivery, now blocked on adding STVCTRE

**Comment by hanars** [comment]
data has been loaded
