### ISSUE TITLE
Change gene symbol for ENSG00000286219

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2301]
**Describe the bug**
seqr lists the gene symbol for ENSG00000286219 as AC242843.1, but the correct symbol should be NOTCH2NLC. AC242843.1 doesn't seem to be listed as an alias in any of the databases I've checked (HGNC, ensembl, NCBI). This is a disease-associated gene in which we expect to return a pathogenic variant, so it would be nice to have the correct symbol. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/summary_data/gene_info/ENSG00000286219

**Scope of the bug**

**Screenshots**

**Comment by hanars** [comment]
This is the gene name for that ensembl ID in the gencode 31 release, which is the latest gencode release seqr has, so its not really a bug. Do you want me to update seqr to a more recent gencode release?

**Comment by Caustint** [comment]
Ah, got it. I assume upgrading gencode releases is a non-trivial amount of
work. Is it something you do at a regular cadence?


*Christina Austin-Tse, PhD, FACMG*
Analysis Team Lead, Rare Disease Group, Broad Institute of MIT and Harvard
Clinical Molecular Geneticist, Center for Genomic Medicine, Massachusetts
General Hospital
Instructor in Pathology, Harvard Medical School
Pronouns: She/her

**Comment by hanars** [comment]
It's not trivial, especially because every time I've done it I immediately get a bunch of complaints that variants are now being listed in the "wrong" gene - there's always at least a couple discovery variants that change name. That said, it is objectively necessary to periodically update. We don't have any sort of regular cadence for it, and it looks like we haven't updated since 2019 so we are probably overdue. So I think this is a call you and Anne need to make

**Comment by Caustint** [comment]
Got it, thanks for the context! I will discuss with Anne and get back to
you.

**Comment by hanars** [comment]
@Caustint did we decide if we want to update gencode in seqr?

**Comment by lynnpais** [comment]
Closing this ticket as it will be done with the next gencode release/ gnomAD update
