### ISSUE TITLE
Remove single gene submitted to MME

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2314]
**Is your feature request related to a problem? Please describe.**
In cases where 2-3 have been submitted, a user must delete all submissions to MME and resubmit the gene(s) of interest. 

**Describe the solution you'd like**
It would be handy to be able to remove only one gene at a time from MME in cases where 2-3 have been submitted. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
I'm a little confused by this request - when you click "update submission" you have the ability to change which genes are submitted, including leaving some submitted and only removing one of the genes. Could you maybe provide some screenshots to show where exactly you are encountering this difficulty and what you would like seqr to do instead?

**Comment by lynnpais** [comment]
The Walsh group and I both tried using the update submission method in
MC40700 but it did not seem to work. Is it a bug?

I just tried it out again in
https://seqr.broadinstitute.org/project/R0542_aicardi_wes/family_page/F031437_she_1236/matchmaker_exchange
by removing the check mark on the gene for PPOX, then hit update. The wheel
kept spinning for quite some time, but after that I am still seeing both
genes submitted. Typically, if a gene has been removed, I would also expect
to see 'previous submissions' at the bottom of the page.

[image: Screen Shot 2021-11-22 at 11.50.57 AM.png]

I am going to delete the submission for this case, because I only submitted
the gene to check and do not want to confuse others.

Let me know if you need more information.

**Comment by hanars** [comment]
For MC40700 I currently see one gene submitted and you provided no detail about what "it did not seem to work" means, so I'm a bit lost there. Next time, please provide screenshots as requested because I think it did successfully update so now I have no way of "seeing" what you saw that made you think it wasn't working

For the Aicardi case case you linked, I also only see one submitted gene in seqr. So maybe its a bug where you have to refresh the page to see the update? Again, screenshotes would be really helpful here. If theres another case you can try for this, can you confirm that the behavior of "still seeing both genes submitted" happens aftyer an update (with a screenshot!) and then refresh the page and see if that fixes it?

**Comment by lynnpais** [comment]
Hi Hana,

This is working now. If anything changes, I'll reach out.

Thanks.
