### ISSUE TITLE
Unable to upload a .csv file

### ISSUE THREAD

**Issue by jgserran** [broadinstitute/seqr#2323]
Each week I upload a .csv file containing an export of all applications that were submitted to RGP. I download the file and redact all PHI then I upload it by going to "Edit Families & Individuals" then I click on "Bulk Edit Individuals" and upload the file. A blue message usually appears saying how many families I am adding. However, this week when I try to upload the file, it says that the file cannot be uploaded. [](url)

https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/project_page

This issue has just happened with this weeks file. When I try to upload any other .csv files they are successfully uploaded. I am not sure if there is just an issue with the spreadsheet I am trying to upload. However, I cross checked all of the columns with last week's spreadsheet that was uploaded and they are the same.  

<img width="1052" alt="Screen Shot 2021-11-23 at 2 18 55 PM" src="https://user-images.githubusercontent.com/89798273/143130714-abeea907-2dfd-4894-8b3a-da371a893c94.png">

I have attached the file I am trying to upload - all PHI has been removed. 

[20211122 WeeklySurveySummaryReportV2 - redacted.csv](https://github.com/broadinstitute/seqr/files/7591194/20211122.WeeklySurveySummaryReportV2.-.redacted.csv)

**Comment by hanars** [comment]
Hi thanks so much fo filling out the full ticket, its really helpful for me. 
There are 2 issues with the file you are trying to upload - the first is that I think you messed up the header because the first cell of the file has a bunch of text and it should be the "participant_guid" header

The weirder one is in line 9 in the description field (4th column) it includes the phrase "target detected" (its in the line about testing positive for covid). This line actually looks to our server like some sort of malware trying to be injected so out server is blocking it from being uploaded. Removing the word "detected" from the phrase fixes the issue and I think "only one target" is fine for the end user to see

**Comment by jgserran** [comment]
Hi Hana, I apologize but the file is still not uploading. I am getting a new error after fixing those two that you pointed out. The error is saying that familyId is not in row one. I have attached the new file as well, and an image of the error message. Thank you. 

<img width="983" alt="Screen Shot 2021-11-28 at 4 28 07 PM" src="https://user-images.githubusercontent.com/89798273/143790759-d4267c9e-839a-4dec-88e2-46803720b665.png">


[20211124 WeeklySurveySummaryReportV2 - redacted and uploaded (11.24.2021).csv](https://github.com/broadinstitute/seqr/files/7614628/20211124.WeeklySurveySummaryReportV2.-.redacted.and.uploaded.11.24.2021.csv)

**Comment by hanars** [comment]
Somehow you added a special character to the beginning of the "participant_guid" header column so seqr was not reading it correctly. When I just cleared out that cell and re-added the header it works fine, I'm attaching the edited file here so you can use it
[20211124.WeeklySurveySummaryReportV2.-.redacted.and.uploaded.11.24.2021.csv](https://github.com/broadinstitute/seqr/files/7619550/20211124.WeeklySurveySummaryReportV2.-.redacted.and.uploaded.11.24.2021.csv)

**Comment by jgserran** [comment]
Thank you so much!
