### ISSUE TITLE
Variant display issue

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2335]
**Describe the bug**
Can we follow the same display format we use for heterozygous variants for variant pairs as well? For some recessive variants/ variant pairs, the gene tags are distributed horizontally across the page (image 1), whereas for dominant variants, they are neatly organized on the left-hand side (Image 2). 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F031762_rgp_1726

**Scope of the bug**
Across multiple projects

**Screenshots**

<img width="1129" alt="Image1" src="https://user-images.githubusercontent.com/37872186/144616588-12a0eb94-288d-42fc-8d30-ce3af3e7f1c0.png">

<img width="1142" alt="Image2" src="https://user-images.githubusercontent.com/37872186/144616605-148f8ec1-185c-49af-8b44-b1fb2a2fa729.png">

**Comment by lynnpais** [comment]
Hi Hana,

We reviewed this at our last analyst group meeting and thought it was a bug since it was acting differently from the heterozygous variants. We assumed all variants would follow the new display structure. We genuinely thought it was a bug, and didn't mean to affect your workflow by choosing an incorrect template. 

Here's what we are proposing for displaying compound heterozygous variants - 
<img width="1398" alt="Screen Shot 2021-12-07 at 2 02 13 PM" src="https://user-images.githubusercontent.com/37872186/145248883-874af654-8fe2-4f49-8e17-80d6583a166a.png">

It meets your criteria. 

Thank you.

**Comment by hanars** [comment]
Yes, this proposed layout works fine. I guess I am still confused that the analysts though there was a bug, because this layout has been around for over 2 years and hasn't changed at all recently. So I am also wondering what happened recently that made you suddenly see something different

**Comment by hanars** [comment]
Actually, as I think about this a bit more, we prosed that layout a couple years ago and it was rejected because the way the columns align differently for the different variants made scanning through a list of mixed compound het and homozygous recessive variants really difficult. What about something like this:
![image](https://user-images.githubusercontent.com/24598672/145446597-1018ea16-ed51-4e31-944a-a0d834dcdc7f.png)

Or if you think that takes up too much vertical space, maybe this:
![image](https://user-images.githubusercontent.com/24598672/145448610-20d20509-5d84-4b0b-9762-500657f5ecbc.png)

Also, I totally forgot that we did actually change the variant layout recently. So thats my bad, I'm sorry

**Comment by lynnpais** [comment]
Option 1 is similar to what I proposed yesterday (and I don't there's a difference?), so let's go with that. I It does take a bit more space, but the space is being used effectively. Also, we will still be able to see both variants in a pair of compound hets in a single view, and that's most important. 

Option 2 would confuse users by using a different format from heterozygous variants.

**Comment by lynnpais** [comment]
Ah I see. Your option 1 is best as it is what we follow for hets.

**Comment by hanars** [comment]
this is updated now, let me know if it looks right to you or if theres anything else you want me to tweak
