### ISSUE TITLE
View and edit MME contacts that have been added to a seqr project

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2354]
**Is your feature request related to a problem? Please describe.**
Related to the ticket - update MME contacts for a specific project (Issue #2342), we need a way to view and remove contacts. Right now since we cannot see who is listed, contacts can be added more than once. Also, Samantha Baxter's name is listed everywhere and this needs to be updated. 

**Describe the solution you'd like**
Can we have a way to edit the contact name, and view and remove emails that have been added to a project. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
So I'm a little unclear what exact functionality to implement for this. Every submission has its own unique contact, they are not the same for all the submissions in a project. This is by design, as for projects like RGP we don't necessarily want the same contacts on everything. The bulk add functionality I implemented previously is pretty basic, as it simply adds an email to a contact if its not already there (that button will not add an email to a submission multiple times so that should not be a concern). I guess for removing a contact it could work the same way, remove something if its there, but usually to edit or delete you want to see whats already there and I'm not sure how to do that, since whats already there is different for every submission. Editing the names gets even harder, since the names are not really associated with the emails so it needs to be edited independently, and that could be weird to do in bulk since, again, the emails are all already different. 

I am open to implementing this, but I'm not sure what user experience you would want to "bulk view" the contacts

**Comment by lynnpais** [comment]
Ok, we'll think about how to best implement this.
