### ISSUE TITLE
Track tissue type of each sample in seqr

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2433]
**Is your feature request related to a problem? Please describe.**
The AnVIL metadata file is definitely going to require tissue type be reported for each sample (exome, genome, RNAseq). While there may be more things AnVIL requires, this is something we should be collecting so makes sense to incorporate it when you have time. 

**Describe the solution you'd like**
Probably want only certain values
Whole blood
Monocytes
Lymphoblastoid cell line (LCL)
Saliva
Buccal
Fibroblast
Muscle
Brain
Kidney
Unknown
Other

(not sure if we need other or how to deal with it but always worried something we haven't thought of will come up)

Should be sample level - we've added it to the sample manifest so would like the PMs to be able to upload it when they create a seqr project (or later with other metadata as we will need to try to fill it in more historically also). 

I think the tissue type for RNAseq should be a different field than the inferred tissue type for RNAseq from Ben's pipeline. 

**Describe alternatives you've considered**

**Additional context**
While this won't be the only addition for the AnVIL metadata file, it's one that we definitely need to add - and I'd like to start collecting it now as people will really need it. So I don't want to wait on this until we update the AnVIL metadata file. 

It's also not super urgent - would be good to have in the next month if possible.

**Comment by hanars** [comment]
Some open questions:
- Do we need to display this anywhere in seqr? Or just eventually in the anvil metadata?
- "we've added it to the sample manifest"
  - Can you provide an example of this new file format?
  - Does this mean we only need to support this for new projects being created off that manifest, or do we also need to be able to support adding it to existing projects? If so, is there a special file format we have for this information?

**Comment by jxchong** [comment]
Hi - just jumping in due to overlap. We'd appreciate it being displayed in seqr as it's useful for analysis (especially if you have multiple samples from the same individual). Tissue source was one of the custom fields we had asked about  (https://github.com/broadinstitute/seqr/issues/1758).

**Comment by anneodonnell** [comment]
Agree - it needs to be in seqr, presumably on the family page. 

@jxchong  - realizing we need to line up entry options for the AnVIL tables - can you share what those are planned to be (rather than the list I came up with)?

We need to be able to upload for new samples and also add for samples already in seqr. I'll ask the PMs for the updated sample manifest tomorrow but already started typing this.

**Comment by jxchong** [comment]
Yeah options for values are going to be UBERON codes.

**Comment by hanars** [comment]
re: "we need to line up entry options for the AnVIL tables" - that needs to be out of the scope of this ticket. If we actually want to wait until the updated metadata is agreed on thats fine, but if we want to do this earlier the logistical work of trying to match a standard that will certainly change several more times is just not something I am willing to do. I will start with the options you specify in the ticket, and later when we go in to add it to the AnVIL metadata we can worry about getting everything to match up. 

As an FYI, doing this now is almost certainly not going to save any time getting the AnVIL metadata done, both for the PM team to get the data in to seqr and for me to implement the code changes. We will need to upload new information for almost every project once the metadata is agreed on, and while doing that it is easy enough to also add tissue type. If your intention with this ticket was to "get ahead" on having part of the metadata added, I think we should revisit if this is worth doing now. It seems to me that there is still added value of having tissue type available in seqr sooner rather than later, so I'm happy to do this now in order to show users the tissue type. But if the main reason for doing this is the metadata, then I would like to hold off

Either way, this is blocked on an example of the new manifest

**Comment by jxchong** [comment]
I *think* Anne might mean that she wants to know the potential values for the "tissue type" field, and that has been decided and is highly unlikely to change (the overall tables are still in flux of course). The accepted values for tissue type  will be UBERON codes https://www.ebi.ac.uk/ols/ontologies/uberon

```
"UBERON concepts such as:
tissue - UBERON:0000479
neural tissue - UBERON:0003714
saliva - UBERON:0001836
skin epidermis - UBERON:0001003
muscle tissue - UBERON:0002385
whole blood - UBERON:0000178
bone marrow - UBERON:0002371
buccal mucosa - UBERON:0006956"
```

**Comment by hanars** [comment]
Thanks for the explanation, although still don't think it makes sense to build this functionality around those value. We can always map human-friendly tissue types to those codes as part of the metadata export if need be

**Comment by anneodonnell** [comment]
While the metadata model will change, it's for samples sequenced under GREGoR and at this point, there are no plans to collect data all the prior CMG samples. We may end up trying to for a few high interest cohorts but not for everything. 

I would like to be able to start collecting this prospectively and having a place for the PMs to store it in seqr instead of tracking some other place (since we do eventually need it in seqr) seems more efficient. 

I think we could map the UBERON names (and codes - which definitely should be hidden) on the back end or we could use these names in the sample manifest. We haven't really started collecting this data yet so we still have options. 

It currently looks like this but we likely should add it as a choice from a dropdown menu. 
![image](https://user-images.githubusercontent.com/10407888/153118415-650966ab-b73f-4b39-b0ce-938ea4366e5e.png)

https://docs.google.com/spreadsheets/d/1iqbMbxpoQBru6xz2ptaX2qCjHt4j7BZfbxE5pBh_3B0/edit#gid=0

**Comment by hanars** [comment]
> I would like to be able to start collecting this prospectively and having a place for the PMs to store it in seqr instead of tracking some other place (since we do eventually need it in seqr) seems more efficient.

Can we confirm they aren't already/also tracking it in airtable? Again, if there is actual value to analysis for having this in seqr I'm happy to add it now, but if the idea is to streamline the PM teams workflow I would really rather we wait and do everything at once and actually make a holistic decision about where things should live. In the past, they've been really adamant that all sample level metrics need to be stored in airtable regardless of whether they are in seqr

> I think we could map the UBERON names (and codes - which definitely should be hidden) on the back end or we could use these names in the sample manifest. 

I have a slight preference for collecting human-friendly names and doing the mapping for the report at the time of report generation, rather than collecting and storing the data in a report-optimized human un-optimized way

> We haven't really started collecting this data yet so we still have options.

I can't implement this until I have a file with the definitive data structure. If we are still iterating on what we are collecting then it is too soon for me to start developing this

**Comment by hanars** [comment]
This is now being tracked on the individual level in seqr using the `primary_biosample` field, no further feature updates are needed
