### ISSUE TITLE
Modify the hover over text for SV callset frequencies 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2450]
This was discussed with Anne and the whole team of analysts. 

1) Can you please remove the current hover over text found next to SV callset in the frequency section of seqr searches (see screenshot attached) and replace it with this text: 
"Filter by allele count (AC) among the jointly genotyped samples that were part of Structural Variant (SV) calling for this project. Only an SV that is estimated to be the same SV (type and breakpoints) will be counted as an allele. CNVs called on exomes have unknown breakpoints so similar overlapping CNVs may be counted as an allele."

2) Can you please add this text in the hover over text next to allele counts frequencies for each SV variant on **genomes** (add the text where the red arrow points in the screenshot , below "This callset" and above the line.
"Only an SV that is estimated to be the same SV (type and breakpoints) among the jointly genotyped samples that were part of  SV calling for this project will be counted as an allele. CNVs called on exomes have unknown breakpoints so similar overlapping CNVs may be counted as an allele."

3) Can you please add this text in the hover over text next to allele counts frequencies for each CNV variant on **exomes** (add the text where the red arrow points in the screenshot
"Only a CNV that is estimated to be the same CNV (type and breakpoints) among the jointly genotyped samples that were part of CNV calling for this project will be counted as an allele. CNVs called on exomes have unknown breakpoints so similar overlapping CNVs may be counted as an allele."

**If it is not possible to have a different hover over text for exome or genomes, forget request 3) here and just use the text described in 2).** 

Let me know if you have any questions. Thank you. 

![SV_callset_HoverOverText](https://user-images.githubusercontent.com/84086816/152582176-d9f29d1d-c05f-4d65-ae2d-fde08844fd37.png)
![SV_Callset](https://user-images.githubusercontent.com/84086816/152582910-5f4afe78-68e4-4b74-912f-3184572e8bb0.png)
![Screen Shot 2022-02-04 at 1 21 57 PM](https://user-images.githubusercontent.com/84086816/152583311-749a7425-350c-4446-8363-3b0cd6376d3f.png)

**Comment by hanars** [comment]
Its not really possible to do different text for exomes and genomes, so I will go with the #2 text

**Comment by Glemiret** [comment]
That sounds good, thank you!

**Comment by hanars** [comment]
So for its filtering by AF not just AC and I'm also a little worried that the phrasing is ambiguous and makes it sound like the AC is local to the project, instead of the project and all samples called with it. I would also prefer to be able to use the same wording for 1 and 2 where possible. Here is my proposed update:

1) "Filter by allele count (AC) or by allele frequency (AF) among all the jointly genotyped samples that were part of the Structural Variant (SV) calling for this project. Only an SV that is estimated to be the same SV (type and breakpoints) among jointly genotyped samples will be counted as an allele. CNVs called on exomes have unknown breakpoints so similar overlapping CNVs may be counted as an allele."
2) "Only an SV that is estimated to be the same SV (type and breakpoints) among jointly genotyped samples will be counted as an allele. CNVs called on exomes have unknown breakpoints so similar overlapping CNVs may be counted as an allele."

**Comment by Glemiret** [comment]
I agree with your change for #2. 
You only added "or by allele frequency (AF)" for #1 right? What is the difference of filtering by allele frequency compared to allele count?

**Comment by hanars** [comment]
well we offer both - you can actually set a specific number to filter by allele count, or a decimal number to filter by allele frequency, and all our other documentation specifies both so only listing one here makes it sound like the AF filter doesn't work, only the AC does

**Comment by hanars** [comment]
this is now live
