### ISSUE TITLE
Affected gene not displayed on Translocation call

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#2629]
**Describe the bug**
This translocation call is not listing any genes as affected but the chr7 breakpoint lands within the MEOX2 gene in both IGV and the UCSC browser. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0109795_715627823_f030225_rg

**Scope of the bug**
This is the first I've seen this. 

**Screenshots**
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/44381119/162470323-dbc0adbf-dae2-4e38-831b-948cd977528d.png">

**Comment by hanars** [comment]
This is probably an issue in the underlying data, but I can reach out about this

**Comment by hanars** [comment]
So there is a bug in seqr causing this to be shown as a translocation, when it is actually a Breakend, which means it is an unresolved event. For SVs, seqr only shows genes that would have a known impact by the event, and because the impact of a Breakend is by definition unknown there are never any genes that meet this criteria so no genes are shown. I've spoken to the team that generates the data and they have agreed in future callsets to include genes with no known impact which will fix this issue, and I created https://github.com/broadinstitute/seqr/issues/2634 to track that work

**Comment by hanars** [comment]
The bug for displaying this as a translocation is fixed and it is now correctly showing as a breakend. I am closing this out now and will use https://github.com/broadinstitute/seqr/issues/2634 to track the future work for being able to show genes for these sorts of events
