### ISSUE TITLE
List index out of range issue

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2636]
**Describe the bug**
I am trying to query our data for all variants (1% AF) in this interval chr17:81511760-81511804. I am using the custom search function in the reports section in seqr to do this. When I hit search, I get the error: List index out of range issue. Not entirely sure this is a bug or it has limited use and hence not working.

Is there a better way to search for variants using seqr in the region of interest?

**Link to page(s) where bug is occurring**
Search page - https://seqr.broadinstitute.org/report/custom_search
Bug display page - https://seqr.broadinstitute.org/report/custom_search/ff4f40b979bf076e61b48917512a89ce?page=1&sort=in_omim

**Scope of the bug**
NA

**Screenshots**
<img width="1324" alt="Screen Shot 2022-04-10 at 3 26 07 PM" src="https://user-images.githubusercontent.com/37872186/162636307-8145a8c0-2406-4ee7-b753-9b48f250005d.png">

**Comment by hanars** [comment]
This is an issue of using quality filtering in an all project search which is not well supported. I'll leave the issue open as I think its possible to get it working, but I'm not actually sure this is a new issue so much as that this has never worked. When removing the quality filter the search succeeds, but it does return 0 results: https://seqr.broadinstitute.org/report/custom_search/6ad5da7b17f3bc26c1ee1b73e61dfeb9?page=1&sort=in_omim

I would recommend using chrom-pos-ref-alt notation instead of rsid and see if that works

**Comment by hanars** [comment]
The "list index out of range" bug has been solved so I am closing out the ticket. You can now do an all project search with quality filters applied. The interval search will still time out because that is not a supported search across all project, so I do recommend you change that to a gene search
