### ISSUE TITLE
ClinVar LP/P filter overriding other filters 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2710]
**Describe the bug**
Here is the question: should the ClinVar LP/P filter override any other filters when doing a seqr search? Will a non coding transcript exon variant be returned by a seqr search if it has a ClinVar LP entry even if "non coding transcript exon" is not selected in the annotation section? Anne and I thought so. 
In RGP_248, 2 non coding variants (1 is ClinVar LP) in trans in RNU4ATAC are not returned by seqr recessive searches. Is this a bug in seqr or is this normal behavior? The variant that has a LP entry in ClinVar is not returned if I do a search with just ClinVar LP/P selected as a filter (and nothing else). 

These 2 variants are the answer for this case (RNA seq profile gave us the answer) but these 2 variants were missed by 3 different analysts who analyzed this case in the past. 

I look forward to discuss this case with you and see what you think, thanks!

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F020329_rgp_248/Analyst%20high%20priority

**Scope of the bug**
Just this project

**Screenshots**

![Screen Shot 2022-05-10 at 9 18 32 AM](https://user-images.githubusercontent.com/84086816/167637715-3732cb76-638a-4d09-b599-84f789e02df5.png)

**Comment by Caustint** [comment]
Chiming in as I'm thinking through this... In the example above both variants are in non coding transcripts, but only one of them is  pathogenic in ClinVar. So you'd want the override behavior to be as follows: seqr should return all variant pairs containing _at least one_ P/LP variant, regardless of the annotations for the second hit (ie the presence of one ClinVar P/LP should override the annotation filters for both variants in the pair). Is that right?

**Comment by Glemiret** [comment]
@Caustint  That would be next step, to discuss as a group. My question for this ticket was: is this a bug or is this current seqr behavior?
Before discussing recessive searches, the variant that has a LP entry in ClinVar is **not** returned if I do a search with just ClinVar LP/P selected as a filter (and nothing else). Is this variant not recognized as having a ClinVar entry? Is this a bug?

**Comment by hanars** [comment]
I'm a little confused by the behavior you expect here. Clinvar will override the annotations filter for a specific variant, but thats not a thing for variant pairs. The second variant in the pair is not in clinvar, so unless you include `non_coding_transcript_exon_variant` as an allowed annotation (or an allowed secondary annotation), the pair won't be returned because only the first variant would be returned. I think maybe you should consider adding this as an allowed secondary annotation, but for now search is behaving as expected

**Comment by hanars** [comment]
> the variant that has a LP entry in ClinVar is not returned if I do a search with just ClinVar LP/P selected as a filter (and nothing else).

When I do a search in this family filtered just on clinvar and the gene, I see the variant returned: https://seqr.broadinstitute.org/variant_search/results/5943f0de6496e52a531e4e92ae300da4?page=1&sort=xpos

**Comment by hanars** [comment]
Its the second variant on the search link you provide. I'm not really sure what the bug is

**Comment by Caustint** [comment]
Yes, the variant is returned, it's just displayed as a CLASP1 intronic variant (I assume because seqr picks that impact as the most "severe"): 
![image](https://user-images.githubusercontent.com/67653781/167664783-c0e104b0-8ed4-47b9-b97e-14d3116e845b.png)

**Comment by hanars** [comment]
In general intronic is the least severe consequence, but seqr always prioritizes coding transcripts over non-coding transcripts which is why CLASP1 is chosen by default. We did decide to tweak the behavior to prioritize transcripts that were filtered on in search over those that weren't (https://github.com/broadinstitute/seqr/issues/229) in part because of this case, as this gene is always non coding.

**Comment by Glemiret** [comment]
Thank you both! That makes more sense to me now. 
The RNU4ATAC gene and its disease association is not shown on this display however but clicking on the clinvar link would detail that the path variant is in RNU4ATAC. There was no clinical suspicion for this phenotype so we would not have included this RNA gene in a panel. Anyhow, not an easy one to solve. We should discuss with the analysis team if there is something to learn from this one

**Comment by Glemiret** [comment]
@hanars FYI, we discussed more today after analysis meeting and agree to not modify the seqr searches. We think the best strategy to catch these non coding RNA variant is to do a ClinVar LP/P search for all cases and then manually look for a 2nd hit for recessive disorders.

**Comment by anneodonnell** [comment]
This strategy is really only optimal for CMG analysts - we can't ensure that every seqr user will do it. Let's see if we can try adding some annotation fields for the 2nd variant. We backed off on including all the other fields when we added SpliceAI but we should probably add back noncoding transcript exon variant and take a look if there is any other annotation that we want to also add. The nuance here is adding back noncoding variants that act via a mechanism other than splicing, which is challenging.

**Comment by Caustint** [comment]
I've been experimenting with this tonight and modifying the saved recessive
searches by adding noncoding_transcript_exon_variant to only the first (or
second) hit annotation does not seem return the RNU4ATAC variant pair in
RGP_248. You have to allow noncoding_transcript_exon_variant as a first
*and* second hit annotation to get the RNU4ATAC variant pair back in a
recessive search, but that modification adds hundreds of variants to the
search results so I don't think it's a viable solution.


Hana, is it possible for the ClinVar P/LP classification to override the
need for us to use noncoding_transcript_exon_variant as both a first and
second hit annotation (or is there another way to modify the search
behavior so that we only return noncoding_transcript_exon_variant pairs if
one of the members of the pair is P/LP in ClinVar)?



*Christina Austin-Tse, PhD, FACMG*
Analysis Team Lead, Center for Mendelian Genomics, Broad Institute of MIT
and Harvard
Clinical Molecular Geneticist, Center for Genomic Medicine, Massachusetts
General Hospital
Instructor in Pathology, Harvard Medical School
Pronouns: She/her

**Comment by hanars** [comment]
So actually it is a bug that the pair is not coming back when you allow noncoding_transcript_exon_variant for one of the variants . Clinvar should be overriding the need for variants to have one of the specified annotations, and it's not doing that correctly here. Can you make a bug ticket and include the search where we would expect to see this pair

**Comment by Glemiret** [comment]
Thank you. I am putting a ticket for RGP_248 for recessive permissive search with noncoding_transcript_exon_variant annotation selected for only one hit

**Comment by Glemiret** [comment]
Oh I just saw Chrissy made a ticket. Thanks!
