### ISSUE TITLE
Not analyzed by me filter option

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2857]
**Describe the bug**
If I am remembering correctly, we used to have a 'Not analyzed by me' feature in seqr to filter cases. This does not seem to be there anymore. 

'Not analyzed by me' should return all cases where the user has not analyzed any type of data. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0482_cmg_thaker_wes/project_page

**Scope of the bug**
Across seqr

**Screenshots**
<img width="1206" alt="Screen Shot 2022-07-21 at 1 01 09 PM" src="https://user-images.githubusercontent.com/37872186/180272275-e8622ca2-6c22-4b8c-8c0a-d0902b7a5575.png">

**Comment by hanars** [comment]
I removed that option because its the same thing as selecting both "not analysed" and "analysed by me", and it got really confusing how the old "Not analyzed by me" feature should behave now. The "Not analysed" filter works in combination with the other filters by essentially saying "the criteria I set has not been analysed. So if you choose  "not analysed" and "analysed by me" it shows all the cases you have not analysed regardless of if other users have done analysis, and then if you add a data type filter live SV it will return all the cases you have not done SV analysis on, regadless if you have done other analysis or someone else did SV analysis. Does that make sense?

**Comment by stephditroia** [comment]
The logic above is not working for the [TGG_Shimamura_WES](https://seqr.broadinstitute.org/project/R0554_tgg_shimamura_wes/project_page) project. `Analyzed by me` returns 47 out of 56 families… I want to see the 9 families I’m missing. If I add `not analyzed` to that filter then only 1 family is returned, a family that has not been analyzed by anyone because it is missing proband data. 
<img width="1565" alt="image (1)" src="https://user-images.githubusercontent.com/44381119/186260731-8b6b013f-1db9-4340-b2ee-26d8298bc3d1.png">
<img width="1565" alt="image" src="https://user-images.githubusercontent.com/44381119/186260734-cbf28e20-ca2d-44ac-8577-86af6943014d.png">

**Comment by hanars** [comment]
It works fine if you use your name instead of the "analysed by me" shortcut
<img width="667" alt="Screen Shot 2022-08-23 at 4 39 47 PM" src="https://user-images.githubusercontent.com/24598672/186261252-cf07d233-ac44-4383-923e-7bf4f907b35a.png">

**Comment by stephditroia** [comment]
Ah cool. Thanks!
