### ISSUE TITLE
Update annotations of gCNV calls

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3065]
**Is your feature request related to a problem? Please describe.**
Existing gCNV calls are incorrectly labeled as 'New'. 

**Describe the solution you'd like**
Using the naming system we discussed in the meeting with Alba, update gCNV annotations using 'is latest' column to differentiate between prior rounds of data.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
Calls with `is_latest` column are added to this drive on 11/11/22
https://drive.google.com/drive/u/0/folders/1-hC5mrMms2nNnUDqXGJQw6qNwh0G2Fil

**Comment by hanars** [comment]
**Broader context:**
There is a difference in gCNV calling between joint calling all samples together, and just calling new samples and merging that callset with the old callset. In the case of true joint calling, actual SV events in a specific sample can change, and it is therefore really valuable to show whether a call is new, overlapping or identical. When there is no new joint calling and just merging callsets, the calls for previous samples stay the same, which essentially means they are all identical. Due to how the calling is done, however, the columns we use for indicating if a call is new/overlap/identical are only populated during real joint calling. 

Going forward, we expect almost every callset to be adding samples but NOT joint calling. However, we do want the pipeline to be able to support joint calls if they do happen in the future, but not by default. 

**Needed code changes**

We need to change how the `PREV_IDENTICAL_COL`, `PREV_OVERLAP_COL`, and `PREV_MISSING_COL` are populated. We also need to add an optional flag to the pipeline to indicate whether a callset has been fully joint called, which should be named `--is-new-joint-call`. 

If `--is-new-joint-call` is passed in, the behavior should stay the same as it is now

If `--is-new-joint-call` is not passed in (which will be the default): 

-  `PREV_OVERLAP_COL` and `PREV_MISSING_COL` are always false
- `PREV_IDENTICAL_COL` is True if the `is_latest` is False, and it is False if `is_latest` is True
  -  If a sample was not added in the "latest" round of calling this means the call existed before and is identical to the previous round of calling. If a sample was added in the "latest" round all the calls are all new and we do not want to show flags comparing this sample to previous rounds of loading as there is y definition no previous calls

**Comment by ShifaSZ** [comment]
Do we only need to change the loading pipeline? Or should we also change the seqr?

**Comment by hanars** [comment]
only the pipeline. If you make the changes as described it will result in the seqr display we want

**Comment by ShifaSZ** [comment]
When the `strvctvre_score` is `less_than_50bp`, what value should we use for the field? We use `None` for `not_exonic`. The `less_than_50bp` is a new input value found in the input file for the `strvctvre_score` field.

**Comment by hanars** [comment]
> When the `strvctvre_score` is `less_than_50bp`, what value should we use for the field? We use `None` for `not_exonic`. The `less_than_50bp` is a new input value found in the input file for the `strvctvre_score` field.

We should probably just check if something is a valid float and only load it if it is, rather than hardcode all the possible strings. For genome SVs we use `hl.parse_float` which returns null if the string is not a valid float

**Comment by hanars** [comment]
> The pipeline should keep the existing behavior without the new option to be backward compatible. So, how about changing the option name to `is-merging-sample-call`?

No, the current behavior is buggy and straight up wrong, we want to change the default behavior

**Comment by hanars** [comment]
Added in https://github.com/broadinstitute/seqr-loading-pipelines/pull/375
