### ISSUE TITLE
Give access to "Internal Notes" section

### ISSUE THREAD

**Issue by brmangilog** [broadinstitute/seqr#3134]
**Describe the solution you'd like**
Please give "Internal Notes" access to users evamar@broadinstitute.org and gshah@broadinstitute.org in the Case Review view of projects: 
Rare Genome Project_External_Genomes
Rare Genome Project_External_Genomes_v2
Rare Genomes Project - Exome submission
Rare Genomes Project_External_Exomes
Rare Genomes Project_Genomes_GRU
Rare Genomes Project_Genomes_HMB

**Comment by hanars** [comment]
This was discussed with Jillian in slack. gshah has access, but the user is logging in as shahgula@broadinstitute.org so you need to update the access in the linked Terra workspace to grant access to that email instead. Similarly, evamar has access but the user is accessing seqr with maev@broadinstitute.org so that is the email address you need to add in Terra
