### ISSUE TITLE
Tracking ClinVar submissions in seqr

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3217]
**Is your feature request related to a problem? Please describe.**
Highlight variants in seqr submitted by the Broad RDG to ClinVar

**Describe the solution you'd like**
To better track variants curated and submitted by our team to ClinVar, we’d like to have a tag in seqr (besides the current ClinVar annotation) reflecting this. 

Each time the team makes a submission to ClinVar, Sam Baxter/Lynn will put in a ticket with a file of all variants to be flagged in seqr. 

It will also be useful to have a page where we can view all variants in ClinVar submitted by the Broad RDG, like how we have the Summary Data page for MME submissions. 

Here’s an example of what this might look like:

<img width="1064" alt="Screen Shot 2023-02-15 at 2 33 35 PM" src="https://user-images.githubusercontent.com/37872186/219136138-c24899c7-e91c-4fec-ae76-b658e01b7ef5.png">

If there’s more than one case with the same variant, they would all have the same flag. 

**Describe alternatives you've considered**
Instead of us submitting a file each time, is it possible for seqr to pull info from ClinVar periodically? I looked at the page in ClinVar, but did not see a unique identifier for submissions from the Broad Institute RDG. Here’s one example - https://www.ncbi.nlm.nih.gov/clinvar/variation/1703227/ 

**Additional context**
Here’s a file from Sam with variants from a recent submission to be tracked in seqr - [https://drive.google.com/file/d/1mGPvNyEz8o_4M8RAtrF83uwdeC9JmPQQ/view?usp=sharing](url)

**Comment by hanars** [comment]
> Each time the team makes a submission to ClinVar, Sam Baxter/Lynn will put in a ticket with a file of all variants to be flagged in seqr.

This is not an acceptable solution. We cannot require an engineer to need to do routine work that is part of regular seqr application usage. Whatever we decide to do to implement this must include a way for Sam/ someone like her to go into seqr and do these updates themself

> Instead of us submitting a file each time, is it possible for seqr to pull info from ClinVar periodically?

With the hail backend, saved variants in seqr will be automatically updated from Clinvar pretty regularly. I would strongly prefer to get this data from Clinvar instead of tracking it ourselves if that is an option. 

> I did not see a unique identifier for submissions from the Broad Institute RDG.

The "Submitter" for the clinvar variant you linked in your example is [Broad Institute Rare Disease Group, Broad Institute](https://www.ncbi.nlm.nih.gov/clinvar/submitters/506627/). Would using anything from this submitter be an acceptable way to tell whether it was submitted by us or not?

**Comment by lynnpais** [comment]
If the submitter identifier works, let's go with that!

**Comment by hanars** [comment]
to use the submitter, we would need to update the pipeline. Can you make a corresponding pipeline ticket for that?

**Comment by lynnpais** [comment]
Yes, here's the pipeline ticket [https://github.com/broadinstitute/seqr-loading-pipelines/issues/385](url)

**Comment by hanars** [comment]
also show submitted condition

**Comment by larrybabb** [comment]
for the submitters, consider this...
ClinVar produces a tab-delimited file every release called submission_summary.txt.gz in their ftp folder https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/. It has the clinvar variation_id in col 1, the submitter name in col 10 and the submission id (SCV id) in col 11. If you can join on the clinvar variation_id then you could find the unique submitter names per variant. I think this is the path of least resistance. ClinVar has been reliably providing this file for years, I don't think they will stop without advanced notice since it was requested by the community some time ago. 
Unfortunately this file does not contain the submitter id.  
If you want to map the names to the org ids, there is another file in the same folder as above called [organization_summary.txt](https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/organization_summary.txt) which I presume will match precisely on submitter names (but I have not verified this - and there is a history of clinvar not updating older records with name updates, so it may be suboptimal.)

**Comment by larrybabb** [comment]
For conditions, I'm going to assume you want the list of conditions shown on the clinvar variant page under the "conditions" section.  Since this list is aggregated using the RCV accessions in clinvar you could consider the following approach...

There's a tab-delimited file called [variant_summary.txt.gz](https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/variant_summary.txt.gz) in the `https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/` folder that has the clinvar `VariationID` in col 31, the `RCVAccession` in col 12 and a `PhenotypeList` in col 14.  The `PhenotypeList` is essentially the unique list of conditions names separated with pipe(|) symbols. If any one condition is comprised of multiple diseases/phenotypes then it will have semi-colon(;) separated delimiters. If there are more than 5? disease/phenotypes in one condition then clinvar simply puts (n conditions) for the name where n is the exact number of disease/phenotypes in the set - this is different than the explicit listing on the UI.  
You will need to extract the 3 col values above and then aggregate on the RCV accessions, since there can and will be multiple occurrences across the rows in this file. You can be confident (but check) that when the RCVAccession is the same the phenotypelist should be the same.

**Comment by larrybabb** [comment]
As we discussed in the planning meeting. You can use the clinvar VCF file to get a mapping of clinvar variants to variation_ids to then link the two bits of data above. That VCF file can be found in this directory.  `https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/` (there's also a sibling folder for GRCh37 if that's needed)

**Comment by larrybabb** [comment]
Finally. Here's the clinvar [READ.ME](https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/README) that describes all the files in their FTP site. I would recommend finding the entries in this file for the files you will be working with to read their description in case there are caveats or details that will prevent you from misunderstanding the data you will be extracting and how to best get to it.

**Comment by jklugherz** [comment]
@lynnpais @hanars 
The example screenshot includes the clinical significance next to the submitter. Do we need this too? I missed this when I added the submitters and conditions annotations but the clinical significance for that submission is easy to add.

**Comment by hanars** [comment]
No preference on my end, I defer to Lynn

**Comment by lynnpais** [comment]
@jklugherz sure!

**Comment by hanars** [comment]
I would say that returning to the pipelien, updating the pipeline and waiting for a data run is not "quick" so we should forgo this for now

**Comment by jklugherz** [comment]
btw since I began working on this the Broad submitter name changed and is now [Broad Center for Mendelian Genomics, Broad Institute of MIT and Harvard](https://www.ncbi.nlm.nih.gov/clinvar/submitters/506627/), commenting here just to document that

**Comment by hanars** [comment]
This is now live, see example at https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/saved_variants/variant/SV0127548_381648854_f034133_rg
