### ISSUE TITLE
Gene expression data (TPMs) loaded successfully, but not showing up in seqr UI 

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#3266]
I just loaded TPM expression data from 
gs://tgg-rnaseq/combined_tables/RDG_and_GTEX_tpms_for_all_tissues__with_metadata_pivoted__20230302__latest_samples_for_seqr.tsv.gz
and it loaded successfully
<img width="907" alt="image" src="https://user-images.githubusercontent.com/6240170/222542121-25f22eea-4619-4da5-a49b-a8b90f133005.png">

The data file includes expression values for RGP_1770_3
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/6240170/222542441-59b21300-e10d-44ad-bd66-ebf51d34e568.png">

so I expected to see a "Show Gene Expression" button appear underneath the gene in variant search results and underneath saved variants, but this is not the case:
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F031759_rgp_1770

**Comment by hanars** [comment]
It looks like there is a bug in seqr where the data was added to the wrong project, despite the fact that the project was  clearly specified in the provided TSV

https://seqr.broadinstitute.org/project/R0638_tgg_walsh_rgp_wgs/family_page/F040494_rgp_1770

**Comment by ShifaSZ** [comment]
We may have to pass a sample-to-project mapping into the sample matching function. The existing sample matching condition for the project can be different depending on the presence of the sample-to-project mapping.

**Comment by hanars** [comment]
>  Or, we could remove samples with unmatched projects after sample matching.

This is not a great option as the matching functionality is designed to handle when it needs to find fuzzy matches and creates missing models, so finding a match in the wrong project and validating it after the fact is not a great option. 

At this point, the 2 different ways of calling the `match_sample_ids_to_sample_records` functions have diverged so much that it probably makes sense to split it into 2 different functions with different behavior, and add explicit project-sample handling to the RNA case. We could do something similar to the change I just made in https://github.com/broadinstitute/seqr/pull/3256 to set explicit project-sample pairs

**Comment by ShifaSZ** [comment]
Is the `project` column in the TMP input data file optional or must column? Can the values in the `project` column be missing?

**Comment by hanars** [comment]
The project column is required and should not be missing, although I don't know if we currently have explicit validation for that. In this case the file had the project column and it was set for this sample, the issue is there was also data for the other project included in the file as well so our filter for `individual__family__project__in=projects` was not sufficient to get the correct project

**Comment by ShifaSZ** [comment]
Okay, thanks. I can annotate a new field `Concat-ed` with the sample_id and the project in the sample matching.

While we need to create new RNA samples, if multiple individuals in different internal projects have the same individual id, we pick an individual model and create a new sample model for it because we create a sample model per individual id.
I'm unsure about the behavior we want. Do we want to load the data replicated to all the projects or just load them to one of the projects?

**Comment by hanars** [comment]
this issue has been fixed, feel fee to reload any data that needs updating

**Comment by bw2** [comment]
I've (re)loaded expression data for all samples after adding the "project" column to the table, but I'm not seeing a way to bring up the TPM expression box plots in seqr even though the data loaded successfully. 
For example, seqr posted the notifcation that expression data was loaded for RGP_1840_3  @ https://the-tgg.slack.com/archives/CA620K989/p1687961660759869, but I'm not finding the expression data in the UI  @ https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F031947_rgp_1840

**Comment by hanars** [comment]
Its the "Show gene expression" button under the gene on each variant, I'm seeing them on the page you linked above and they seem to be working fine

**Comment by bw2** [comment]
I see it too now. Thanks
