### ISSUE TITLE
Simplify clearing family.pedigreeDataset

### ISSUE THREAD

**Issue by monkollek** [broadinstitute/seqr#3354]
We have noticed with the BCH instance of seqr that the pedigree is sometimes drawn incorrectly when family is updated including affected status.

The root cause of the problem is the assumption that `family.pedigreeDataset`, which is a `jsonb` stays up to date relative to the database entries. There can scenarios where this is out of sync with what is contained in the postgres database.

Removing it from the line below and just taking information from `individuals` variable resolves the problem.
https://github.com/broadinstitute/seqr/blob/master/ui/shared/components/panel/view-pedigree-image/LazyPedigreeImagePanel.jsx#L176

**Comment by hanars** [comment]
seqr will use the most up-to-date information to draw the pedigree when `family.pedigreeDataset` is null. If `family.pedigreeDataset` has a non-null value, it is because a user edited the pedigree and hit save. The assumption is that if someone went to the trouble of doing that they do not want their hard work to be deleted and that the user-added pedigree data is more robust than the minimal set of data available to the pedigree otherwise. This is not a bug, it is desired behavior.  This may be an issue that your user's workflow does not fit into the expected seqr workflow, so you may want to change your expectations around  users editing pedigrees. 

I will transition this to a feature request to add a "reset" button to make it easy to reset the pedigree to the seqr default drawing and remove the saved updated pedigree, but that will still require a user action after data has been updated as I am not willing to make the default behavior deleting peoples custom pedigrees.
