### ISSUE TITLE
Move In OMIM to top of Sort By options

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3516]
**Is your feature request related to a problem? Please describe.**
Important to sort variants returned in a search by known disease genes and hence requesting to move the option to the top of the Sort By options 

**Describe the solution you'd like**
Move In OMIM to top of Sort By options in a variant search

<img width="1326" alt="Screenshot 2023-07-27 at 11 17 51 AM" src="https://github.com/broadinstitute/seqr/assets/37872186/64bd2e22-ecae-4105-8008-eaf4feaebdc8">

Also, some behavior seems to have changed. The Sort by now defaults to Protein consequence, even though I always change it to OMIM. This has happened in at least 4 cases this week. Previously, it would remember previous behavior and default to the last used. 

**Describe alternatives you've considered**
NA

**Additional context**
Discussed with Anne at a recent seqr workshop

**Comment by hanars** [comment]
> The Sort by now defaults to Protein consequence, even though I always change it to OMIM. This has happened in at least 4 cases this week. Previously, it would remember previous behavior and default to the last used.

Thats an unrelated issue, if you want that investigated and fixed, it needs its own bug ticket. Putting information about bugs in the description of an unrelated feature request is not sufficient to get them fixed

In geenral, when you try to group work that might be related into a single tickets it makes more work for our team, not less. Its easier for us to work on a couple tickets at once if they do turn out to be easier to do at the same time than it is to try and do 2 unrelated things in one ticket. Tickets should encompass a deliverable work item. Unless you actually do not want us to rearrange the sort options in this ticket unless this bug is also fixed, they can be released separately, which means 2 tickets

**Comment by lynnpais** [comment]
The Sort By behavior I mentioned earlier seems to have resolved. This ticket is solely to Move 'In OMIM' to top of Sort By options.

**Comment by hanars** [comment]
updated
