### ISSUE TITLE
Show Gene Expression button often missing

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#3592]
**Describe the bug**
RNA and gene expression data is frequently not showing up for me on families across different projects where RNAseq data is loaded. I've selected one sample where the tag is intermittently showing up to illustrate this. 

RNAseq is loaded for family HK011. 

When I do a gene search, the "show gene expression" only appears on TRAPPC9 (which happens to be the diagnosis in this case but maybe shows up because I've clicked it before). The button is not there on other variants. https://seqr.broadinstitute.org/variant_search/results/f933780a2ca63264f2f04396852c4c86?page=1&sort=xpos

If I select gene search, it does show up for some genes but not for others. I don't see a consistent behavior here. 

There are also problems with it not showing up on the saved variant page. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/f933780a2ca63264f2f04396852c4c86?page=1&sort=xpos
Example but I've checked other projects with RNAseq data and see the same thing https://seqr.broadinstitute.org/variant_search/results/1adf761d3597a366ce57435850fd368f?page=1&sort=xpos

**Scope of the bug**
Generally across seqr

**Screenshots**
![image](https://github.com/broadinstitute/seqr/assets/10407888/b4620244-0a71-49e4-a7fd-eff809a2187d)

The show gene expression blue box at the bottom is what I'm referencing here.

**Comment by hanars** [comment]
Gene expression data is not available on every gene, and there was also [this feature update](https://github.com/broadinstitute/seqr/issues/3285)where we did not load expression data for genes where the expression was 0. That has been fixed but unless dta is relaoded we will not show expression for genes with an expression of 0. The fix for this is to request that the expression data be reloaded
