### ISSUE TITLE
Research options for changelog with RSS feed

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3645]
**Is your feature request related to a problem? Please describe.**
End users are not kept in the loop about certain feature changes and updates which might impact how they use seqr. 

**Describe the solution you'd like**
For the MVP, we would like to have a changelog with RSS feature on the project page in seqt. It should be manageable by Lynn/ other TGG users. Hana - can you look into suitable ways to accomplish this? Ben suggested - https://medium.com/@vilcins/rss-feeds-for-your-github-releases-tags-and-activity-cbda2c51373

**Describe alternatives you've considered**
NA

**Additional context**
Discussed this morning.

**Comment by hanars** [comment]
The github options described here are not good options for us, as these are automatically generated feeds by github that include changes based on user activity and pull requests and code changes. They are potentially useful if you are a local seqruser that wants to be notified every time the seqr repo changes, but that is already an option for such users, and they should have the technical know-how to set that up on their own. For this chnagelog, we want a human managed solution, not an automated one

**Comment by hanars** [comment]
Although actually, they do have an automated feed for discussions, so that might be a good solution. We could create a  discussion category just for the changelog (maybe. name it changelog? or something more friendly?) that only we could post to, and then Lynn could post updates there as appropriate. If we are okay using github discussions as our chnagelog, I think that would be easiest. @lynnpais thoughts?

This would be the link for the rss feed for the "general" channel in discussions, but it would be very easy
https://github.com/broadinstitute/seqr/discussions/categories/General.atom

**Comment by lynnpais** [comment]
Yes, this could work. We can also think about adding a link somewhere on the project page to alert users to check this and/or sign up for notifications.
