### ISSUE TITLE
Update display for FATHMM, Polyphen, SIFT 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3729]
**Is your feature request related to a problem? Please describe.**
Need to update scores and how they are shown in seqr based on new guidelines published by ClinGen.

**Describe the solution you'd like**
For FATHMM, Polyphen, & SIFT, use new colors and ranges as described below

Benign: Very strong + Strong = dark green
Benign: Moderate + Supporting = light green
VUS: In between ranges benign supporting and pathogenic supporting = Grey
Pathogenic Supporting = orange
Pathogenic Moderate = red
Pathogenic Strong + very strong = dark red

The cutoff ranges can also be found here in Table 2 - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9748256/ or this image 
<img width="965" alt="255224354-089a5837-7cf6-490a-8f9e-8a608dda497d" src="https://github.com/broadinstitute/seqr/assets/37872186/3e3add07-cb4e-4901-aa90-ddb9b6469ab5">

**Describe alternatives you've considered**
NA

**Additional context**
Scores require pipeline updates. Ticket here - https://github.com/broadinstitute/seqr-loading-pipelines/issues/616

**Comment by hanars** [comment]
@lynnpais can you do a sanity check for me and confirm that these ranges correspond to the ranges specified in the tabe? I got a little it confused because fathmm and sift scores are worse as they get lower instead of higher so I think these ended up being correct bt would like verificaion:

<img width="262" alt="Screenshot 2024-01-04 at 5 41 42 PM" src="https://github.com/broadinstitute/seqr/assets/24598672/9d1b89fe-230b-49df-bc4b-545169e89308">
<img width="271" alt="Screenshot 2024-01-04 at 5 42 05 PM" src="https://github.com/broadinstitute/seqr/assets/24598672/0f17977d-9ec7-4ea2-8fed-3c4998919e3c">
<img width="263" alt="Screenshot 2024-01-04 at 5 42 18 PM" src="https://github.com/broadinstitute/seqr/assets/24598672/a9b6001e-fc80-415a-b63b-31a25ccbb240">

**Comment by hanars** [comment]
updated in hail backend, will go live with MVP

**Comment by lynnpais** [comment]
@hanars verified that lower scores for FATHMM and SIFT indicate pathogenicity, ie. values in table are correct. Just fyi, "A SIFT score is a normalized probability of observing the new amino acid at that position, and ranges from 0 to 1. A value of between 0 and 0.05 is predicted to affect protein function." So, lower score, the site is more intolerant to variation.

**Comment by hanars** [comment]
these are now live
