### ISSUE TITLE
Individual metadata report

### ISSUE THREAD

**Issue by sambaxter** [broadinstitute/seqr#3778]
**Is your feature request related to a problem? Please describe.**
We will update the Sample metadata report to be "Individual metadata" and update the field included, and the logic behind the fields to agree with the GREGoR AnVIL data model

**Describe the solution you'd like**
Please update the new individual metadata sheet to include the fields in column A of [this sheet](https://docs.google.com/spreadsheets/d/1pluDJN57tXS7QhyG2_J9HPMa6jP2cWtifDkMLse7PVU/edit#gid=860014992)

**Additional context**
Add any other context, links to relevant seqr pages, or screenshots about the feature request here.

**Comment by hanars** [comment]
This has been updated

**Comment by stephditroia** [comment]
Related to https://github.com/broadinstitute/seqr/issues/3731, I am still finding examples of `variant_inheritance` = `de novo` in cases without data for one or both parents. I'm wondering if it is because `maternal ID` and `paternal ID` exist in seqr without data. If so, can we update the logic to check data is loaded?

Examples: 
RGP_2107_3
RGP_2133_3
RGP_2142_3
RGP_2172_3
RGP_2263_3
RGP_2273_3
RGP_2325_3
RGP_2333_3
RGP_2396_3
RGP_2530_3
RGP_2587_3
RGP_2626_3

I've found this bug everywhere that lists `variant_inheritance` (participant metadata, the variant metadata, and GREGoR findings report) as well as in the family metadata under `actual_inheritance`.

**Comment by hanars** [comment]
As a general rule, tickets will only ever be reopened within like a day or two of them being closed, in the case that after we close them we realize they are not actually done. Discovering a different edge case 3 months later always requires a new ticket
