### ISSUE TITLE
Clinvar Prefilter fields are throwing an exception.

### ISSUE THREAD

**Issue by bpblanken** [broadinstitute/seqr#3973]
**Describe the bug**
Clinvar Path fields are throwing an exception. 

```

  File "/hail_search/queries/mito.py", line 147, in _get_family_passes_quality_filter
42
    clinvar_path_ht = False if passes_quality is None else self._get_loaded_clinvar_prefilter_ht(pathogenicity)
41
  File "/hail_search/queries/mito.py", line 167, in _get_loaded_clinvar_prefilter_ht
40
    return self._get_loaded_filter_ht(
39
  File "/hail_search/queries/mito.py", line 161, in _get_loaded_filter_ht
38
    ht = ht.filter(ht_filter(ht))
37
  File "/hail_search/queries/mito.py", line 176, in <lambda>
36
    return lambda ht: ht.is_pathogenic
35
  File "/usr/local/lib/python3.9/dist-packages/hail/table.py", line 168, in __getattr__
34
    raise AttributeError(get_nice_attr_error(self, item))
33
AttributeError: Table instance has no field, method, or property 'is_pathogenic'
32
    Did you mean:
31
        Data fields: 'pathogenic' [row], 'likely_pathogenic' [row]
```

**Comment by hanars** [comment]
Is this for all data types and builds or isolated to a subset of the prefilter tables?

**Comment by bpblanken** [comment]
```
I'm looking at the prefilters, I don't think they've changed.  they're all pathogenic or likely_pathogenic
```

**Comment by bpblanken** [comment]
Ok, I'm investigating.  I think the pipeline has been writing `pathogenic` and `likely_pathogenic` since the [first iteration of these prefilters](https://github.com/broadinstitute/seqr-loading-pipelines/pull/556/files#diff-982d56a3e5ca7e0ebb8060542f720a9a332499bf0d937031be9dafe40864e069R25-R52)

**Comment by hanars** [comment]
According to git blame seqr has been rusing those field names for at least 6 months, and our test fixtures have those field names

**Comment by bpblanken** [comment]
😬 ... ok it seems possible this has never worked correctly?  did we recently change how we were accessing the table?  I think we did?

**Comment by bpblanken** [comment]
I'm more than happy to change on my end, whatever we think is easiest.

**Comment by hanars** [comment]
There was [this](https://github.com/broadinstitute/seqr/pull/3945/files) that is a syntax change to how we were accessing the prefilter tables which is maybe what you are remembering, but all the logic change was around the AF table not the clinvar table, and you'll note there was no change in this PR to the clinvar prefilter fixture table because the usage of that tale did not actually change

**Comment by hanars** [comment]
I think its easies to change on your end, if thats okay? I like the syntax better since `is` makes it clear that htis is a boolean value

**Comment by hanars** [comment]
Also the git blame on the seqr repo shows these were the fields since before September 2023 and that initial script commit from the pipeline is October. So I think what happened is we manually generated the initial table at some point, and then when you actually went to put it in the repo the code you wrote to generate it never matched what we had hacked together in the first place

**Comment by bpblanken** [comment]
Ok, I can fix on my end!

**Comment by bpblanken** [comment]
Alrighty, pipeline pr is [here](https://github.com/broadinstitute/seqr-loading-pipelines/pull/732) and I manually changed the tables.
