### ISSUE TITLE
Error in GREGoR Report Page

### ISSUE THREAD

**Issue by apham98** [broadinstitute/seqr#3989]
**Describe the bug**
I'm receiving the following error in the GREGoR report page for validating and uploading GRU data: "The following entries are missing required "primary_biosample" in the "analyte" table: Broad_BON_B20-08_1_1, Broad_BON_B20_33_1_D1, Broad_BON_B20_42_1_D1, Broad_BON_UC563_1_D1."

However, I do see "primary_biosample" is populated when going in the actual seqr project page. I'm listing the family pages below for reference:
[Family: BON_B20-08](https://seqr.broadinstitute.org/project/R0565_mgrc_bonnemann_wgs/family_page/F041766_bon_b20_08)
[Family: BON_B20_33](https://seqr.broadinstitute.org/project/R0565_mgrc_bonnemann_wgs/family_page/F041772_bon_b20_33)
[Family: BON_B20_42](https://seqr.broadinstitute.org/project/R0565_mgrc_bonnemann_wgs/family_page/F041762_bon_b20_42)
[Family: BON_UC563](https://seqr.broadinstitute.org/project/R0565_mgrc_bonnemann_wgs/family_page/F041764_bon_uc563)

AnVIL path for reference: gs://fc-secure-94bfa40c-b8d8-47ae-8611-a2d771ac2022

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/report/gregor

**Scope of the bug**
Only experiencing for this page for GRU tables. The HMB tables worked fine and have been validated/uploaded. 

**Screenshots**
![Screenshot 2024-03-21 at 4 42 14 PM](https://github.com/broadinstitute/seqr/assets/108075186/31e5b3b3-4358-4eb7-bf54-21dc629c5eda)
![Screenshot 2024-03-21 at 4 42 32 PM](https://github.com/broadinstitute/seqr/assets/108075186/b1accf83-6329-4798-b0fe-b87af7694f82)

**Comment by hanars** [comment]
This error is complaining about the analyte table, not the participant table. The analyte table pulls airtable data, and for RNA data field this comes from the `Primary_Biosample` in the airtable data, not the seqr primary biosample. Its very confusing! But basically for RNA data we have to use airtable as the source of truth, not seqr, because RNA can have a different biosample than the biosample that was originally submitted for dna variant calling
