### ISSUE TITLE
Variant metadata not populating with discoveries for GSS site

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#4062]
**Describe the bug**
Stanford site is having trouble getting their variant metadata to populate. They have discovery tags on variants. When clicking 'view all my projects' on the variant metadata page, Discovery variants in the Seqr_Demo project are returned but not in any Stanford specific project. 

**Link to page(s) where bug is occurring**
Project with discovery tags: https://seqr.broadinstitute.org/project/R0742_gss_anvil_seqr_test/project_page
Empty variant metadata: https://seqr.broadinstitute.org/summary_data/variant_metadata/R0742_gss_anvil_seqr_test

**Scope of the bug**
This is a problem with all of the stanford projects. 

**Screenshots**
GSS_AnVIL_Seqr_test variant metadata: 
![image](https://github.com/broadinstitute/seqr/assets/44381119/8c2c2432-12ab-486a-9586-6c1f3378ec9e)
'view all my projects' variant metadata: 
![image](https://github.com/broadinstitute/seqr/assets/44381119/b7cc8e7c-a274-4575-94aa-047480cfcb5f)

**Comment by hanars** [comment]
Variant Metadata is only reported for the proband, as determined by the individual in the family who has the "Proband Relationship" set to self. It looks like they have not populated the proband relationship field

**Comment by stephditroia** [comment]
Did not catch that! Thanks.

**Comment by stephditroia** [comment]
It looks like their family page is missing the field to update an individuals proband-relationship status. Is there a way to give them access to this locked field? Or is there an alternative way to fix this metadata? 

![image](https://github.com/broadinstitute/seqr/assets/44381119/13a41b47-51fd-4211-a7a8-12e337bdf720)

**Comment by hanars** [comment]
proband relationship is an internal-only field and I do not feel comfortable exposing it further. It seems like maybe we were premature in exposing this report to non-internal gregor projects. While I was comfortable making this report available broadly when it seemed like minimal work, it seems that in fact that very specific logic we need to make our gregor reporting work is not broadly applicable to other projects. 

It is not entirely clear to me why specifically they need to be downloading this report, instead of going to the project saved variants page, filtering to discovery variants, and hitting download.

**Comment by hanars** [comment]
This report was moved as part of this feature request, designed ot make this report work for local insatlls. Making it available to external users on the Broad's instance was an unintended side effect, and one I do not think we should support. I have reopened [the original ticket](https://github.com/broadinstitute/seqr/issues/3881#issuecomment-2093633444 ) and will redo the implementation tomkae these reports available to local users but not to our external users
