### ISSUE TITLE
Cap MME submissions

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4378]
**Is your feature request related to a problem? Please describe.**
A user recently submitted >20 genes to MME which goes against best practices.  

**Describe the solution you'd like**
Cap individual gene submissions to MME at 5. A user may remove a submission and submit another candidate but the total number of genes should not exceed 5 per case at any given time. 

SVs can include several genes and would be an exception as it is one event. 

**Describe alternatives you've considered**
NA

**Additional context**
Reviewed this plan with Chrissy.

**Comment by hanars** [comment]
As a note, SVs have to be submitted in a specific gene, you do not submit every gene an SV overlaps. So like in this screenshot there are 4 genes you can submit but its actually only 2 variants, because 3 of those genes are all in the same SV
<img width="660" alt="Screenshot 2024-09-17 at 11 22 05 PM" src="https://github.com/user-attachments/assets/10784233-3205-4e18-b339-775702709aed">

**Comment by hanars** [comment]
This is now live. Existing submissions will not be changed, only new submissions will be disabled
