### ISSUE TITLE
In Silico Filters

### ISSUE THREAD

**Issue by paolomaccallini-hub** [broadinstitute/seqr#4420]
The error "Internal Server Error" is generated when using some in silico filters. I noticed it using SIFT and FATHMM, in particular.

![image](https://github.com/user-attachments/assets/b7e39597-4806-4962-9f49-61c8d54f020a)

**Comment by hanars** [comment]
Hello, we need more information to resolve this issue. In the future, it is crucial that you submit bugs by selecting the bug report issue template and fill out every required field, or our team will not be able to help you: https://github.com/broadinstitute/seqr/issues/new/choose

This ticket is missing links to where the bug is occurring and information about the scope of the bug

**Comment by lynnpais** [comment]
Closing for lack of information.
