### ISSUE TITLE
Permission errors trying to load or edit bam files for IGV

### ISSUE THREAD

**Issue by pfpetrowski** [broadinstitute/seqr#4424]
**Describe the bug**
When I click the `Edit IGV` button I would expect to be able to add and/or replace bam files for the chosen sample. But I am instead hit with a "permission denied" error in spite of being the owner of the underlying project.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0780_gss_anvil_seqr/family_page/F058890_gss1672

**Scope of the bug**
I first observed this issue in the `GSS_Anvil_Seqr` project, but I also have it in the `GSS_Anvil_Seqr_test` project. I get this error for older samples that have already had IGV enabled by the broad, and for freshly loaded samples where I'm loading bam files for the first time.

**Screenshots**
![Screenshot 2024-10-14 at 12 26 41 PM](https://github.com/user-attachments/assets/6a6a446e-cfdd-4f6c-b1bf-d9a9bf1eb4be)

**Comment by hanars** [comment]
This is not a problem with your personal level of permission on the seqr project, it is that the seqr service account does not have read access to the underlying workspace where your CRAMs are stored. While this access must be grated at loading time, if you have since revoked seqr's access you will be unable to add or view IGV in your project. To re-grant access, you can start the process of requesting more data loading on the project page and go thrugh the first step, where you select the checkbox agreeing to grant seqr access

**Comment by pfpetrowski** [comment]
I ran through that first step as recommended but unfortunately it hasn't made a difference. We loaded new data just last week which required us to go through the full process.Since then we haven't done anything that would have caused the service accounts permissions to be revoked. Should I expect to see seqr service account show up as a collaborator in my anvil workspace?

**Comment by hanars** [comment]
Yes, there should be a seqr service account listed in your workspace collaborators. If it is not there, this means that there are security settings on your workspace that are restricting seqr's access, and seqr will not be able to show IGV from that workspace until that is resolved

**Comment by pfpetrowski** [comment]
I'm commenting to note that this issue has been resolved. @lynnpais mentioned that other bug fixes related to this feature have been implemented and my assumption is that this issue was resolved incidentally . Perhaps someone with more knowledge than I could address the specific updates that were made.
