### ISSUE TITLE
create single source reference data tables

### ISSUE THREAD

**Issue by jklugherz** [broadinstitute/seqr#4471]
- New configs (name, version, function) to write from raw table to parsed table - one per source
- Create the tables and add code to create them programmatically inside the pipeline to rewrite them if hashed config version is different 
- it's all about partitioning!

**Comment by hanars** [comment]
Heres all the datasources we will need to implement, divided up somewhat arbitrarily. Let me now if you want to swap anything around or if theres anything I missed. I ma purposefully leaving out `high_constraint_region_mito` because theres an open PR to remove it from seqr (https://github.com/broadinstitute/seqr/pull/4478)

Julia:
- cadd
- hgmd
- mpc
- primate_ai
- gnomad_exomes
- gnomad_genomes
- gnomad_qc
- gnomad_mito
- gnomad_non_coding_constraint
- screen
- local_constraint_mito

Hana:
- dbnsfp
- dbnsfp_mito
- eigen
- splice_ai
- topmed
- exac
- mitomap
- mitimpact
- hmtvar
- helix_mito

Ben:
- clinvar
- clinvar_mito
