### ISSUE TITLE
Add BGE as a data type in seqr

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#4536]
**Is your feature request related to a problem? Please describe.**
I noticed that the Wave 2 NeuroDev data (which is blended genome exome data or BGE) has been loaded as WGS data. I can see that there was probably a need for that given that there will be calls outside of the exome, but there are issues with classifying BGE as WGS given that the WGS is very low coverage (SNV/indel calls in the noncoding regions will be unreliable so we wouldn't want people to expect to get the same level of info they would out of a true genome).

**Describe the solution you'd like**
Could we add BGE as a new data type option in seqr (it really is a unique data type, sort of in between WES and WGS)?

**Describe alternatives you've considered**
Open to other proposals 

**Additional context**
Discussed briefly with Anne and she agreed. Not high priority.

**Comment by hanars** [comment]
We are not fully supporting BGE in seqr at this time. There appears to have been a communication error here - @lynnpais in the future we need to be better about communicating when we are doing limited released/one off hacks. There are numerous engineering changes we would need to do to truly support BGE data in seqr, including but not limited to the request in this ticket. We intentionally chose to load data for this project as WGS data instead of waiting to add the support for BGE data before loading. I apologize that this was not communicated properly 

I am closing this ticket as we will be addressing this in more targeted ticket when we decide to actually add BGE support

**Comment by lynnpais** [comment]
@hanars I talked to Emily about this ticket since she's been analyzing this data. I think the idea was to have a different name in a few places in seqr such as the Family Page to indicate this is BGE data, so it is not confused with WGS data. I don't think Chrissy's request was for any pipeline changes. Anyway, I wanted to discuss with Chrissy/ the analysts further. We'll do that, and can add it to the larger BGE work.

**Comment by hanars** [comment]
> I think the idea was to have a different name in a few places in seqr such as the Family Page to indicate this is BGE data, so it is not confused with WGS data

So when we talked about adding BGE data to seqr we specifically decided not to do any engineering work to support it and said we would load it as WGS data, which we did. These sorts of feature change are now not possible at this point - we loaded the data as WGS data and thats how it is in seqr. Nothing in seqr makes this data any different from all the other wgs data loaded in seqr, there is no way to somehow label it as WGS in some places and BGE in others. I'm sorry if it was not clear that this is what "loading it as WGS data" would result in. 

> I don't think Chrissy's request was for any pipeline changes

These sorts of changes require us to fully support a new sample type in seqr all the way through in the pipeline, there is no way to load data as one type in the pipeline and a different type in seqr

**Comment by Caustint** [comment]
Sounds like I didn't have the full context and Anne was probably too busy to think it through when we discussed briefly. Neurodev has a fairly narrow userbase (mostly Emily, Ike, and I) so I don't anticipate it being a big issue for that project. Just something to keep in mind for when full support for BGE data is implemented!
